# -*- coding: utf-8 -*-
"""SchwarMAX-analytic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YolNejOJX8gbPyZOsI_gZTVNYLUvawBI
"""

from google.colab import drive
drive.mount('/content/drive')

# ! pip install numpyro
# # ! pip install jax_cosmo
# ! pip install arviz
! pip install jaxopt
! pip install corner
! pip install emcee

path = '/content/drive/MyDrive/SchwarMAX-analytic/'

import sys
sys.path.append(path)

from model_bar import *
from likelihoods_bar import *
from utils import *
from sample_from_density import sample_from_density_grid

import os
# os.environ["JAX_ENABLE_X64"] = "True"

import jax
# jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import jax.numpy.linalg as jnn
import pandas as pd
import numpy as np
import scipy as sp
import pickle

import emcee
import corner
import matplotlib.pyplot as plt

from constants import EPSILON

path = '/content/drive/MyDrive/SchwarMAX-analytic/'
filename = 'mock_Nbody_bar_XY_withRot_Nbins1000.pkl'
dict_data = get_dict_data_bootstrap(path, filename)

def log_prior(theta,):
    if (7 < theta[0] < 12) and (8 < theta[1] < 12) and (-1 < theta[2] < 2) and (-1 < theta[3] < 1) and (-1 < theta[4] < 1)\
    and (0 <= theta[5] < jnp.pi) and (0 <= theta[6] < jnp.pi/2) and (0 <= theta[7] < jnp.pi):
        return 0.0  # log(1) = 0 for uniform prior
    return -np.inf  # log(0) = -inf for out-of-bounds

def log_prob(theta,):
    # print(theta)
    lp = log_prior(theta)
    if not np.isfinite(lp):
        return -np.inf

    ll = logl_density(theta, dict_data, dict_data['total_bins'])

    return ll + lp

ndim = 8
nwalkers = 16  # must be >= 2 * ndim

# Initialize walkers around ground truth
# p0 = np.array([ground_truth[k] for k in param_names])
p0 = np.array([10.5, 10, 0.8, 0., 0.5, jnp.pi/4, jnp.pi/4, 3.5*jnp.pi/4])
# initial_pos = p0 + 1e-1 * np.random.randn(nwalkers, ndim)
np.random.seed(42)
initial_pos = p0 + np.random.uniform(-0.3, 0.3, (nwalkers, ndim))

sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob)
sampler.run_mcmc(initial_pos, 500, progress=True)

samples = sampler.get_chain(discard=200, flat=True)


params_bestfit = np.percentile(samples, axis=0, q=50)
logl_val = logl_density(params_bestfit, dict_data, dict_data['total_bins'])
print('Best-fit logL projection', logl_val)#

dict_data['logl_density_max'] = logl_val

logM_disc_best_fit, logM_bulge_best_fit, \
logRd_disc_best_fit, logHs_disc_best_fit, logRs_bulge_best_fit, \
alpha_best_fit, beta_best_fit, gamma_best_fit = params_bestfit
# logMhalo_best_fit, logrho0_best_fit, logM_bulge_best_fit, logRh_disk_best_fit, logRs_disk_best_fit, logHs_disk_best_fit, logRs_bulge_best_fit,\
#       alpha_best_fit, beta_best_fit, gamma_best_fit, logLM_best_fit = (11.8, 8.8, 10.4, 1.2, 0.45, -0.24, -0.1, 30*np.pi/180, 20*np.pi/180, 0*np.pi/180, 0)

print('logM_disc_best_fit',logM_disc_best_fit)
print('logM_bulge_best_fit',logM_bulge_best_fit)
print('logRd_disc_best_fit',logRd_disc_best_fit)
print('logHs_disc_best_fit',logHs_disc_best_fit)
print('logRs_bulge_best_fit',logRs_bulge_best_fit)
print('alpha_best_fit',alpha_best_fit * 180 / np.pi)
print('beta_best_fit',beta_best_fit * 180 / np.pi)
print('gamma_best_fit',gamma_best_fit * 180 / np.pi)

# @jax.jit
# def potential_func(x, y, z, dict_phi, params_halo):
#     """ Returns Phi(R, z) """
#     phi_halo = NFW_potential(x, y, z, params_halo)
#     phi_disk = evaluate_phi_axisymmetric(x, y, z, dict_phi)
#     return phi_halo + phi_disk

# @jax.jit
# def density_func(x, y, z, params):
#     """ Returns Stellar Density nu(R, z) """
#     # Double Exponential Disk
#     val = DoubleExponentialDisk_density(x, y, z, params) + Dehnen_density(x, y, z, params)
#     return val

# bounds = jnp.array(
#     [
#         [-15.0, 15.0],  # x
#         [-15.0, 15.0],  # y
#         [-5.0, 5.0],    # z
#     ],
#     dtype=jnp.float32,
# )

# n_samples = 10_000
# n_x,n_y,n_z = 48, 48, 32
# key = jax.random.PRNGKey(0)
# sample_ic_dict = sample_from_density_grid(
#     key,
#     density_func,
#     params_disk_rho,
#     bounds,
#     n_samples=n_samples,
#     n_x=n_x,
#     n_y=n_y,
#     n_z=n_z,
# )
# samples = np.asarray(sample_ic_dict["samples"])
# dict_data['w0'] = samples

# n_samples = 10_000
# samples_x = np.random.normal(0.0, 4.0, size=(n_samples,))
# samples_y = np.random.normal(0.0, 4.0, size=(n_samples,))
# samples_z = np.random.normal(0.0, 2.0, size=(n_samples,))
# w0 = jnp.array([samples_x, samples_y, samples_z]).T

# dict_data['w0'] = w0

ground_truth = [
    11.9,
    logM_disc_best_fit,
    logM_bulge_best_fit,
    jnp.log10(19).item(),
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit, #  10 * np.pi/180,
    beta_best_fit,
    gamma_best_fit,
    0.,
    1.5,

    -2., # sigma_xy model term
]
logL = logl_angular_input_bootstrap(ground_truth, dict_data, dict_data['total_bins'])
print(logL)

import time
start = time.time()
logL = logl_angular_input_bootstrap(ground_truth, dict_data, dict_data['total_bins'])
logL.block_until_ready()  # Ensure computation finishes before timing
end = time.time()
print('time per logl evaluation', end - start, 's')
print(logL)

fig, ax = plt.subplots(1,2,figsize=(10,3))

logL_ls = []
for i in tqdm(range (0, 9)):
  params_i = [
    11.9,
    logM_disc_best_fit,
    logM_bulge_best_fit,
    jnp.log10(19).item(),
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit,
    beta_best_fit,
    gamma_best_fit,
    0.,
    1.5,

    -2.,
  ]
  params_i[-3] = params_i[-3] + (i-4)/10
  logL = logl_angular_input_bootstrap(params_i, dict_data, dict_data['total_bins'])
  logL.block_until_ready()  # Ensure computation finishes before timing
  print('L/M=', 10**params_i[-3], logL)
  logL_ls.append(logL)

ax[0].plot(np.arange(-4,5)/10 + ground_truth[-3], logL_ls - np.amin(np.isfinite(logL_ls)))
ax[0].set(xlabel = 'log10 (L/M)')

logL_ls = []
for i in tqdm(range (0, 9)):
  params_i = [
    11.9,
    logM_disc_best_fit,
    logM_bulge_best_fit,
    jnp.log10(19).item(),
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit,
    beta_best_fit,
    gamma_best_fit,
    0.,
    1.5,

    -2.,
  ]
  params_i[-2] = params_i[-2] + (i-4)/10
  logL = logl_angular_input_bootstrap(params_i, dict_data, dict_data['total_bins'])
  logL.block_until_ready()  # Ensure computation finishes before timing
  logL_ls.append(logL)
  print('Omega=', 10**params_i[-2], logL)

ax[1].plot(np.arange(-4,5)/10 + ground_truth[-2], logL_ls - np.amin(np.isfinite(logL_ls)))
ax[1].set(xlabel = 'log10 (Omega)')

ground_truth = [
    11.6,
    logM_disc_best_fit,
    logM_bulge_best_fit,
    jnp.log10(19).item(),
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit,
    beta_best_fit,
    gamma_best_fit,
    -0.,
    1.5,

    -2.,
]
logL = logl_angular_input_bootstrap(ground_truth, dict_data, dict_data['total_bins'])
print(logL)

import time
start = time.time()
logL = logl_angular_input_bootstrap(ground_truth, dict_data, dict_data['total_bins'])
logL.block_until_ready()  # Ensure computation finishes before timing
end = time.time()
print('time per logl evaluation', end - start)
print(logL)

prior_uniform_low =  [
    ground_truth[0] - 3,
    ground_truth[1] - 3,
    ground_truth[2] - 3,
    ground_truth[3] - 1,
    ground_truth[4] - 1,
    ground_truth[5] - 1,
    ground_truth[6] - 1,
    0,
    0,
    0,
    -2.,
    0.,

    -5,
]
prior_uniform_high = [
    ground_truth[0] + 3,
    ground_truth[1] + 3,
    ground_truth[2] + 3,
    ground_truth[3] + 1,
    ground_truth[4] + 1,
    ground_truth[5] + 1,
    ground_truth[6] + 1,
    jnp.pi,
    jnp.pi/2,
    jnp.pi,
    2.,
    2.,

    -0.5,
]

def log_prior(params):
    lp = 0
    for i in range (0, ndim):
        if (params[i]<=prior_uniform_low[i]) | (params[i]>=prior_uniform_high[i]):
            lp+= -jnp.inf
    return lp

def log_prob(theta):
    params = theta
    lp = log_prior(params)
    if not np.isfinite(lp):
        return -np.inf
    ll = float(logl_angular_input_bootstrap(params, dict_data, dict_data['total_bins']))  # convert from JAX array
    if not np.isfinite(ll):
        return -np.inf
    return lp + ll

# --- trace state ---
trace = {
    "iter": 0,
    "nfev_local": 0,
    "best_f": np.inf,
    "best_x": None,
}

def neg_log_prob_traced(theta):
    f = -log_prob(theta)   # your existing log_prob
    trace["nfev_local"] += 1

    if np.isfinite(f) and f < trace["best_f"]:
        trace["best_f"] = f
        trace["best_x"] = np.array(theta, copy=True)

    # optional: print every N function evaluations (not every call)
    if trace["nfev_local"] % 20 == 0:
        print(f"[eval {trace['nfev_local']:5d}] f={f:.6f} best={trace['best_f']:.6f}")

    return f

def cb(xk):
    trace["iter"] += 1
    print(
        f"[iter {trace['iter']:4d}] "
        f"nfev={trace['nfev_local']:5d} "
        f"best_f={trace['best_f']:.6f} "
        f"x0={xk[0]:.4f}"
    )

x0 = np.array(ground_truth, dtype=float)  # use numpy array for scipy

min_results = sp.optimize.minimize(
    neg_log_prob_traced,
    x0,
    method="Nelder-Mead",
    callback=cb,
    options={
        "maxiter": 200,
        "xatol": 1e-1,      # better than global tol for Nelder-Mead
        "fatol": 1e-1,
        "return_all": True, # keeps per-iteration x history
        "disp": True
    },
)

print("Done:", min_results.message)
print("nit =", min_results.nit, "nfev =", min_results.nfev)

res = min_results.x
print(np.round(res, 2))

np.save(path+'/minimise_0323_Nbins1000', res)


# ==============================================================

ndim = 13
nwalkers = int(ndim * 2)  # must be >= 2 * ndim

np.random.seed(42)

# Initialize walkers around ground truth
# p0 = ground_truth
p0 = res
initial_pos = np.zeros((nwalkers, ndim))
initial_pos[:, :7] = np.vstack([p0[:7]]*nwalkers) * np.ones((nwalkers, 7)) + np.random.uniform(-0.2, 0.2, (nwalkers, 7))
initial_pos[:,7:9] = np.vstack([p0[7:9]]*nwalkers) * np.ones((nwalkers, 2)) + np.random.uniform(-0.1, 0.1, (nwalkers, 2))
initial_pos[:,7:9] = np.clip(initial_pos[:,7:9], a_min=0, a_max=np.vstack([[jnp.pi, jnp.pi/2]]*nwalkers))
initial_pos[:,  9] =  p0[9] + np.random.uniform(-0.3, 0.3, nwalkers) # gamma
initial_pos[:,  10] = p0[10] + np.random.uniform(-0.5, 0.5, nwalkers)
initial_pos[:,  11] = p0[11] + np.random.uniform(-0.4, 0.4, nwalkers)
initial_pos[:, 12:13] = np.vstack([p0[12:13]]*nwalkers) * np.ones((nwalkers, 1)) + np.random.uniform(-0.4, 0.4, (nwalkers, 1))

backend = emcee.backends.HDFBackend(path+'/backend_0323_Nbins1000_noDens.csv')
backend.reset(nwalkers, ndim)
sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=backend)
sampler.run_mcmc(initial_pos, 200, progress=True)

# # Restart the sampler from the backend
# backend = emcee.backends.HDFBackend(path+'/backend_0306.csv')
# sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, backend=backend)
# state = backend.get_last_sample()   # this is an emcee.State
# print('restarted from the state:', state)
# sampler.run_mcmc(state, 100, progress=True)   # adds 500 more steps

samples = sampler.get_chain(discard=80, flat=True)

param_names = ['logM_halo','logM_disk','logM_bar', 'logRs_halo', 'logRs_disk', 'logHs_disk', 'logL_bar', 'alpha', 'beta', 'gamma', 'log_light_to_mass_ratio', 'log_Omega', 'log_sigma']
import pandas as pd
pd.DataFrame(samples, columns=param_names).to_csv(path+'/test_posterior_0323_Nbins1000_noDens.csv', index=False)

samples_raw = sampler.get_chain(discard=0, flat=False)
log_prob_raw = sampler.get_log_prob(discard=0, flat=False)
with open(path+'/test_posterior_WholeChain_0323_Nbins1000_noDens.pkl', 'wb') as f:
    pickle.dump(samples_raw, f)
with open(path+'/test_posterior_logprob_0323_Nbins1000_noDens.pkl', 'wb') as f:
    pickle.dump(log_prob_raw, f)