# -*- coding: utf-8 -*-
"""SchwarMAX-MCMC_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ad4ErLpKHC1n9r0yZSRp4c7SXVmOyHTv
"""

from google.colab import drive
drive.mount('/content/drive')

# ! pip install numpyro
# # ! pip install jax_cosmo
# ! pip install arviz
! pip install jaxopt
! pip install corner
! pip install emcee

path = '/content/drive/MyDrive/SchwarMAX-MCMC/'

import sys
sys.path.append(path)

from model import *
from likelihoods import *
from utils import *
from sample_from_density import sample_from_density_grid
from CylindricalSpline import get_phi_m, evaluate_phi_axisymmetric

# import os
# os.environ["JAX_ENABLE_X64"] = "True"

import jax
# jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import jax.numpy.linalg as jnn
import pandas as pd
import numpy as np
import scipy as sp
import pickle

import emcee
import corner
import matplotlib.pyplot as plt

from constants import EPSILON

import time

def get_dict_data(path):

    with open(path + 'mock_Nbody_bar_XY_withRot.pkl', 'rb') as f:
        bin_dict = pickle.load(f)

    # voronoi binning mapping and data
    num_per_bin = jnp.array(bin_dict['num_per_bin'])
    total_bins = jnp.array(bin_dict['total_bins'])
    bin_mapping = jnp.array(bin_dict['bin_mapping'])
    surface_density = jnp.array(bin_dict['surface_density'])
    V_data = jnp.array(bin_dict['V_mean'])
    sigma_data = jnp.array(bin_dict['V_sigma'])
    h1_data = jnp.array(bin_dict['h1'])
    h2_data = jnp.array(bin_dict['h2'])
    h3_data = jnp.array(bin_dict['h3'])
    h4_data = jnp.array(bin_dict['h4'])
    v0 = jnp.array(bin_dict['v0'])
    s = jnp.array(bin_dict['s'])
    alpha, beta, gamma = bin_dict['orientation']

    # V_data_err = jnp.where(0.1 * jnp.fabs(V_data) < 10, 10, 0.1 * V_data)
    # sigma_data_err = jnp.where(0.1 * jnp.fabs(sigma_data) < 5, 5, 0.1 * sigma_data)
    # h1_data_err = jnp.where(0.1 * jnp.fabs(h1_data) < 0.03, 0.03, 0.1 * jnp.fabs(h1_data))
    # h2_data_err = jnp.where(0.1 * jnp.fabs(h2_data) < 0.03, 0.03, 0.1 * jnp.fabs(h2_data))
    # h3_data_err = jnp.where(0.1 * jnp.fabs(h3_data) < 0.03, 0.03, 0.1 * jnp.fabs(h3_data))
    # h4_data_err = jnp.where(0.1 * jnp.fabs(h4_data) < 0.03, 0.03, 0.1 * jnp.fabs(h4_data))
    V_data_err = jnp.array(bin_dict['V_mean_err'])
    sigma_data_err = jnp.array(bin_dict['V_sigma_err'])
    h1_data_err = jnp.array(bin_dict['h1_err'])
    h2_data_err = jnp.array(bin_dict['h2_err'])
    h3_data_err = jnp.array(bin_dict['h3_err'])
    h4_data_err = jnp.array(bin_dict['h4_err'])

    # df_Rzphi_data = pd.read_csv(path + 'mock_axisymmetric_disc_Rzphi.csv')
    # Rzphi_density_data = jnp.array(df_Rzphi_data['mass'].to_numpy()).astype(jnp.float32)
    with open(path + 'mock_axisymmetric_disc_Rzphi.pkl', 'rb') as f:
        Rzphi_density_data = pickle.load(f)

    R_grid, z_grid, phi_grid = Rzphi_density_data['R_grid'], Rzphi_density_data['z_grid'], Rzphi_density_data['phi_grid']
    dR = np.unique(R_grid)[1] - np.unique(R_grid)[0]
    dz = np.unique(z_grid)[1] - np.unique(z_grid)[0]
    dphi = np.unique(phi_grid)[1] - np.unique(phi_grid)[0]
    sample_for_integration = Rzphi_density_data['sample_for_integration']

    from scipy.stats import qmc
    X_regular_grid, Y_regular_grid = bin_dict['X_regular_grid'], bin_dict['Y_regular_grid']
    dX = jnp.unique(X_regular_grid)[1] - jnp.unique(X_regular_grid)[0]
    dY = jnp.unique(Y_regular_grid)[1] - jnp.unique(Y_regular_grid)[0]
    sampler = qmc.Sobol(d=3, scramble=False)
    sample = sampler.random_base2(m=10)


    dict_data = {
        # 'w0': w0,
        'v0': v0,
        's': s,

        # 'Rzphi_density_data': Rzphi_density_data,
        'XY_density_data': surface_density,
        'V_data': V_data,
        'V_data_err': V_data_err,
        'sigma_data': sigma_data,
        'sigma_data_err': sigma_data_err,
        'h1_data': h1_data,
        'h1_data_err': h1_data_err,
        'h2_data': h2_data,
        'h2_data_err': h2_data_err,
        'h3_data': h3_data,
        'h3_data_err': h3_data_err,
        'h4_data': h4_data,
        'h4_data_err': h4_data_err,
        'num_per_bin': num_per_bin,
        'bin_mapping': bin_mapping,
        'total_bins': total_bins.item(),

        'R_grid': R_grid,
        'z_grid': z_grid,
        'phi_grid': phi_grid,
        'dR': dR,
        'dz': dz,
        'dphi': dphi,
        'sample_for_integration': sample_for_integration,

        'X_regular_grid': X_regular_grid,
        'Y_regular_grid': Y_regular_grid,
        'dX': dX,
        'dY': dY,
        'sample_for_integration_XY': sample,
    }

    return dict_data

path = '/content/drive/MyDrive/SchwarMAX-MCMC/'
dict_data = get_dict_data(path)

def log_prior(theta,):
    if (6 < theta[0] < 10) and (8 < theta[1] < 12) and (-1 < theta[2] < 2) and (-1 < theta[3] < 1) and (-1 < theta[4] < 1)\
    and (0 <= theta[5] < jnp.pi) and (0 <= theta[6] < jnp.pi/2) and (0 <= theta[7] < jnp.pi):
        return 0.0  # log(1) = 0 for uniform prior
    return -np.inf  # log(0) = -inf for out-of-bounds

def log_prob(theta,):
    # print(theta)
    lp = log_prior(theta)
    if not np.isfinite(lp):
        return -np.inf

    ll = logl_density(theta, dict_data, dict_data['total_bins'])

    return ll + lp

ndim = 8
nwalkers = 16  # must be >= 2 * ndim

# Initialize walkers around ground truth
# p0 = np.array([ground_truth[k] for k in param_names])
p0 = np.array([9.2, 10, 0.3, 0., 0., jnp.pi/4, jnp.pi/4, jnp.pi/4])
# initial_pos = p0 + 1e-1 * np.random.randn(nwalkers, ndim)
np.random.seed(42)
initial_pos = p0 + np.random.uniform(-0.3, 0.3, (nwalkers, ndim))

sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob)
sampler.run_mcmc(initial_pos, 500, progress=True)

samples = sampler.get_chain(discard=200, flat=True)


params_bestfit = np.percentile(samples, axis=0, q=50)
logl_val = logl_density(params_bestfit, dict_data, dict_data['total_bins'])
print('Best-fit logL projection', logl_val)#

dict_data['logl_density_max'] = logl_val

logrho0_best_fit, logM_bulge_best_fit, \
logRd_disc_best_fit, logHs_disc_best_fit, logRs_bulge_best_fit, \
alpha_best_fit, beta_best_fit, gamma_best_fit = params_bestfit
# logMhalo_best_fit, logrho0_best_fit, logM_bulge_best_fit, logRh_disk_best_fit, logRs_disk_best_fit, logHs_disk_best_fit, logRs_bulge_best_fit,\
#       alpha_best_fit, beta_best_fit, gamma_best_fit, logLM_best_fit = (11.8, 8.8, 10.4, 1.2, 0.45, -0.24, -0.1, 30*np.pi/180, 20*np.pi/180, 0*np.pi/180, 0)

print('logrho0_best_fit',logrho0_best_fit)
print('logM_bulge_best_fit',logM_bulge_best_fit)
print('logRd_disc_best_fit',logRd_disc_best_fit)
print('logHs_disk_best_fit',logHs_disc_best_fit)
print('logRs_bulge_best_fit',logRs_bulge_best_fit)
print('alpha_best_fit',alpha_best_fit * 180 / np.pi)
print('beta_best_fit',beta_best_fit * 180 / np.pi)
print('gamma_best_fit',gamma_best_fit * 180 / np.pi)

params_halo_pot = {
    'logM': 11.8,
    'Rs':19,
    'a':1.0,
    'b':1.0,
    'c':1.0,
    'x_origin':0.0,
    'y_origin':0.0,
    'z_origin':0.0,
    'dirx':0.0,
    'diry':0.0,
    'dirz':1.0
}

params_disk_rho = {
    'rho0_disc': 10 ** logrho0_best_fit,
    'Rd_disc': 10 ** logRd_disc_best_fit,
    'hz_disc': 10 ** logHs_disc_best_fit,
    'x_origin': 0.0,
    'y_origin': 0.0,
    'z_origin': 0.0,
    'dirx': 0.0,
    'diry': 0.0,
    'dirz': 1.0,
    'alpha': alpha_best_fit * 180 / jnp.pi,
    'beta': beta_best_fit * 180 / jnp.pi,
    'gamma': gamma_best_fit * 180 / jnp.pi,
    'light_to_mass_ratio': 1,
    'logM_bulge': logM_bulge_best_fit,
    'Rs_bulge': 10 ** logRs_bulge_best_fit,
}

@jax.jit
def potential_func(x, y, z, dict_phi, params_halo):
    """ Returns Phi(R, z) """
    phi_halo = NFW_potential(x, y, z, params_halo)
    phi_disk = evaluate_phi_axisymmetric(x, y, z, dict_phi)
    return phi_halo + phi_disk

@jax.jit
def density_func(x, y, z, params):
    """ Returns Stellar Density nu(R, z) """
    # Double Exponential Disk
    val = DoubleExponentialDisk_density(x, y, z, params) + Dehnen_density(x, y, z, params)
    return val

bounds = jnp.array(
    [
        [-15.0, 15.0],  # x
        [-15.0, 15.0],  # y
        [-5.0, 5.0],    # z
    ],
    dtype=jnp.float32,
)

n_samples = 20_000
# n_x,n_y,n_z = 48, 48, 32

# key = jax.random.PRNGKey(0)
# sample_ic_dict = sample_from_density_grid(
#     key,
#     density_func,
#     params_disk_rho,
#     bounds,
#     n_samples=n_samples,
#     n_x=n_x,
#     n_y=n_y,
#     n_z=n_z,
# )
# samples = np.asarray(sample_ic_dict["samples"])
# dict_data['w0'] = samples

samples_x = np.random.normal(0.0, 5.0, size=(n_samples,))
samples_y = np.random.normal(0.0, 5.0, size=(n_samples,))
samples_z = np.random.normal(0.0, 2.5, size=(n_samples,))
w0 = jnp.array([samples_x, samples_y, samples_z]).T
dict_data['w0'] = w0



ground_truth = [
    11.5,
    logrho0_best_fit,
    logM_bulge_best_fit,
    jnp.log10(19).item(),
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit,
    beta_best_fit,
    gamma_best_fit,
    0.2,
    1.61
]
# ground_truth = [
#     11.1875, 10.08161914 , 9.96619078 , 0.9975036 ,  0.76423168, -0.6755621,
#     0.76472051 , 0.40915259 , 0.15521095 , 2.15984495, -0.875      , 1.475
#     ]

start = time.time()
logL = logl_angular_input(ground_truth, dict_data, dict_data['total_bins'])
logL.block_until_ready()  # Ensure computation finishes before timing
end = time.time()
print('time per logl evaluation', end - start, 's')
print(logL)

import time
start = time.time()
logL = logl_angular_input(ground_truth, dict_data, dict_data['total_bins'])
logL.block_until_ready()  # Ensure computation finishes before timing
end = time.time()
print('time per logl evaluation', end - start, 's')
print(logL)

logL_ls = []
for i in tqdm(range (0, 30)):
  logL = logl_angular_input(ground_truth, dict_data, dict_data['total_bins'])
  logL_ls.append(logL)
  print(logL)
plt.hist(logL_ls, bins = 50)

jax.config.update("jax_log_compiles", True)

def log_prior(params):
    lp = 0
    for i in range (0, ndim):
        if (params[i]<=prior_uniform_low[i]) & (params[i]>=prior_uniform_high[i]):
            lp+= -jnp.inf
    return lp

def log_prob(theta):
    params = theta
    lp = log_prior(params)
    if not np.isfinite(lp):
        return -np.inf
    ll = float(logl_angular_input(params, dict_data, dict_data['total_bins']))  # convert from JAX array
    if not np.isfinite(ll):
        return -np.inf
    return lp + ll

ground_truth = [
    11.5,
    logrho0_best_fit,
    logM_bulge_best_fit,
    jnp.log10(19).item(),
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit,
    beta_best_fit,
    gamma_best_fit,
    0.,
    1.6
]
prior_uniform_low =  [
    ground_truth[0] - 3,
    ground_truth[1] - 3,
    ground_truth[2] - 3,
    ground_truth[3]- 1,
    ground_truth[4]- 1,
    ground_truth[5]- 1,
    ground_truth[6]- 1,
    0,
    0,
    0,
    -2,
    0
]
prior_uniform_high = [
    ground_truth[0] + 3,
    ground_truth[1] + 3,
    ground_truth[2] + 3,
    ground_truth[3]+ 1,
    ground_truth[4]+ 1,
    ground_truth[5]+ 1,
    ground_truth[6]+ 1,
    jnp.pi,
    jnp.pi/2,
    jnp.pi,
    2,
    2
]

ndim = 12

n_grid = 1024
param_grid = pd.read_csv(path + '/quasi_random_samples_12D_unity.csv').to_numpy()
index = np.random.choice(len(param_grid), size=n_grid, replace=False)
param_grid = param_grid[index]
param_grid[:, 0] = (param_grid[:, 0] - 0.5) * 3 + ground_truth[0]
param_grid[:, 1] = (param_grid[:, 1] - 0.5) * 3 + ground_truth[1]
param_grid[:, 2] = (param_grid[:, 2] - 0.5) * 3 + ground_truth[2]
param_grid[:, 3] = (param_grid[:, 3] - 0.5) * 1.5 + ground_truth[3]
param_grid[:, 4] = (param_grid[:, 4] - 0.5) * 1.5 + ground_truth[4]
param_grid[:, 5] = (param_grid[:, 5] - 0.5) * 1.5 + ground_truth[5]
param_grid[:, 6] = (param_grid[:, 6] - 0.5) * 1.5 + ground_truth[6]
param_grid[:, 7] = (param_grid[:, 7] - 0.5) * 0.3 * jnp.pi + ground_truth[7]
param_grid[:, 8] = (param_grid[:, 8] - 0.5) * 0.3 * jnp.pi + ground_truth[8]
param_grid[:, 9] = (param_grid[:, 9]      ) * 1 * jnp.pi
param_grid[:, 10] = (param_grid[:, 10] - 0.5) * 2
param_grid[:, 11] = (param_grid[:, 11] - 0.5) * 0.4 + ground_truth[11]

from tqdm import tqdm
log_prob_grid = []
for i in tqdm(range(n_grid)):
  logl = log_prob(param_grid[i])
  log_prob_grid.append(logl)
  print(np.round(param_grid[i], 2), 'logL:', logl, "cache:", logl_angular_input._cache_size())

log_prob_grid = np.array(log_prob_grid)

pd.DataFrame({
    'logM_halo': param_grid[:, 0],
    'logM_disk': param_grid[:, 1],
    'logM_bulge': param_grid[:, 2],
    'logRs_halo': param_grid[:, 3],
    'logRs_disk': param_grid[:, 4],
    'logHs_disk': param_grid[:, 5],
    'logRs_bulge': param_grid[:, 6],
    'alpha': param_grid[:, 7],
    'beta': param_grid[:, 8],
    'gamma': param_grid[:, 9],
    'log_light_to_mass_ratio': param_grid[:, 10],
    'log_Omega': param_grid[:, 11],
    'log_prob': log_prob_grid,
}).to_csv(path + '/grid_search_result_0306.csv', index=False)

print("cache:", logl_angular_input._cache_size())

from google.colab import runtime
runtime.unassign()



"""# Test stochasticity"""

path = '/content/drive/MyDrive/SchwarMAX-MCMC/'
dict_data = get_dict_data(path)

logMhalo_best_fit, logrho0_best_fit, logM_bar_best_fit, logRh_disk_best_fit, logRs_disk_best_fit, logHs_disk_best_fit, logRs_bar_best_fit,\
    alpha_best_fit, beta_best_fit, gamma_best_fit, logLM_best_fit, logOmega_bar = (11.8, 8.8, 10.4, 1.2, 0.45, -0.24, 0.3,
                                                                                    30*np.pi/180, 20*np.pi/180, 130*np.pi/180, 0, 1.6)

# logMhalo_best_fit, logrho0_best_fit, logM_bar_best_fit, logRh_disk_best_fit, logRs_disk_best_fit, logHs_disk_best_fit, logRs_bar_best_fit,\
#     alpha_best_fit, beta_best_fit, gamma_best_fit, logLM_best_fit, logOmega_bar = (10.07, 9.22, 9.2, 1.95, 0.54, -0.94, 0.35, 0.73, 0.71, 2.45, -0.25, 1.48)


alpha = alpha_best_fit * 180/np.pi
beta = beta_best_fit * 180/np.pi
gamma = gamma_best_fit * 180/np.pi
ground_truth = [logMhalo_best_fit,
                logrho0_best_fit,
                logM_bar_best_fit,
                logRh_disk_best_fit,
                logRs_disk_best_fit,
                logHs_disk_best_fit,
                logRs_bar_best_fit,
                alpha,
                beta,
                gamma,
                logLM_best_fit,
                logOmega_bar,
]


params_halo_pot = {
    'logM': ground_truth[0],
    'Rs':10 ** ground_truth[3],
    'a':1.0,
    'b':1.0,
    'c':1.0,
    'x_origin':0.0,
    'y_origin':0.0,
    'z_origin':0.0,
    'dirx':0.0,
    'diry':0.0,
    'dirz':1.0
}

params_dict = {
    'rho0_disc': 10 ** ground_truth[1],
    'Rd_disc': 10 ** ground_truth[4],
    'hz_disc': 10 ** ground_truth[5],
    'light_to_mass_ratio': 10 ** ground_truth[10],
    'x_origin': 0.0,
    'y_origin': 0.0,
    'z_origin': 0.0,
    'dirx': 0.0,
    'diry': 0.0,
    'dirz': 1.0,
    'alpha': ground_truth[7],
    'beta': ground_truth[8],
    'gamma': ground_truth[9],
    'logM_bar': ground_truth[2],
    'Rs_bar': 10 ** ground_truth[6],
    'Omega_bar': 10 ** ground_truth[11],
    'p_bar': 0.3,
    'q_bar': 0.3,
}

samples = np.array([
    np.random.normal(0, 5, 20000),
    np.random.normal(0, 5, 20000),
    np.random.normal(0, 2, 20000)
]).T


w0 = jnp.array(samples)
n_particles = w0.shape[0]
params_disk_rho = params_dict
NR, NZ, Rmin, Rmax, Zmin, Zmax, Mmax = 50, 30, 1e-3, 30.0, 1e-3, 15.0, 8.
Nphi = 300
N_int = 10_000
dict_phi = get_phi_m(density_func, params_disk_rho, NR, NZ, Rmin, Rmax, Zmin, Zmax, Mmax, Nphi, N_int)

#=========================================== GET INITIAL VELOCITY ===================================================
@jax.jit
def dPhi_dz(x, y, z, dict_phi, params_halo):
    # Numerical derivative of Potential w.r.t z
    d = 5e-3
    return (potential_func(x, y, z+d, dict_phi, params_halo) - potential_func(x, y, z-d, dict_phi, params_halo)) / (2*d)

@jax.jit
def dPhi_dR(x, y, z, dict_phi, params_halo):
    # Numerical derivative of Potential w.r.t R
    d = 5e-3
    R = jnp.sqrt(x**2 + y**2)
    return (potential_func(R+d, 0, z, dict_phi, params_halo) - potential_func(R-d, 0, z, dict_phi, params_halo)) / (2*d)

@jax.jit
def get_jeans_moments(x_star, y_star, z_star, dict_phi, params_disc, params_halo, anisotropy_b=1.0):
    """
    Computes (v_mean, sigma_R, sigma_z, sigma_phi) for a star at (R, z).

    Parameters:
    -----------
    x_star, y_star, z_star : float
        Coordinates of the particle.
    density_fn : function
        Function returning stellar density nu(R, z).
    anisotropy_b : float
        sigma_R^2 / sigma_z^2. Default 1.0 (isotropic).
    """
    R_star = jnp.sqrt(x_star**2 + y_star**2)

    # --- Step 1: Compute Sigma_z (Vertical Integration) ---

    # Integrand: nu(R, z) * dPhi/dz
    def integrand(z_prime):
        return density_func(x_star, y_star, z_prime, params_disc) * dPhi_dz(x_star, y_star, z_prime, dict_phi, params_halo)

    # Integrate from z_star to infinity (e.g., 20 kpc)
    # Note: We assume symmetry, so we integrate |z| to infinity
    pts = jnp.linspace(jnp.abs(z_star), 10.0, 1000)
    dx = pts[1] - pts[0]
    # integrand_val = integrand(pts)
    integrand_val = jax.vmap(integrand, in_axes = (0))(pts)
    integral_val = jsp.integrate.trapezoid(integrand_val, pts, dx)

    nu_val = density_func(x_star, y_star, z_star, params_disc)
    # if nu_val <= 0: return 0, 0, 0, 0

    sigma_z2 = (1.0 / nu_val) * integral_val

    sigma_z2 = jnp.maximum(sigma_z2, 0.0)

    sigma_z = jnp.sqrt(sigma_z2)

    # --- Step 2: Compute Sigma_R (Anisotropy assumption) ---
    sigma_R2 = anisotropy_b * sigma_z2
    sigma_R = jnp.sqrt(sigma_R2)

    # --- Step 3: Compute v_phi_total^2 (Radial Equation) ---
    # We need d(nu * sigma_R^2) / dR
    # Since sigma_R^2 = b * sigma_z^2, we need d(b * Integral) / dR

    # Define a helper to calculate the "Vertical Pressure" P_zz = nu * sigma_z^2 at any R
    def vertical_pressure(r_in):
        # We need to re-integrate at radius r_in to get the pressure there
        def integrand_r(z_prime):
            return density_func(r_in, 0, z_prime, params_disc) * dPhi_dz(r_in, 0, z_prime, dict_phi, params_halo)

        pts = jnp.linspace(jnp.abs(z_star), 10.0, 1000)
        dx = pts[1] - pts[0]
        # integrand_val = integrand(pts)
        integrand_val = jax.vmap(integrand_r, in_axes = (0))(pts)
        integral_val = jsp.integrate.trapezoid(integrand_val, pts, dx)
        return integral_val # This is (nu * sigma_z^2)

    # Calculate derivative w.r.t R using central difference
    dR = 5e-3
    Pzz_plus = vertical_pressure(R_star + dR)
    Pzz_minus = vertical_pressure(R_star - dR)
    d_nu_sigR2_dR = anisotropy_b * (Pzz_plus - Pzz_minus) / (2*dR)

    # Radial Jeans Equation:
    # v_phi_sq = sigma_R^2 + (R/nu) * d(nu*sigR^2)/dR + R * dPhi/dR
    term1 = sigma_R2
    term2 = (R_star / nu_val) * d_nu_sigR2_dR
    term3 = R_star * dPhi_dR(x_star, y_star, z_star, dict_phi, params_halo)

    v_phi_total_sq = term1 + term2 + term3

    # --- Step 4: Separate Rotation vs Dispersion ---
    # Assumption: sigma_phi approx sigma_R (Round velocity ellipsoid in plane)
    sigma_phi = sigma_R

    v_streaming_sq = v_phi_total_sq - sigma_phi**2

    v_streaming_sq = jnp.maximum(v_streaming_sq, 0.0)
    v_mean_phi = jnp.sqrt(v_streaming_sq)

    output = jax.lax.cond(nu_val<=0, lambda: (0.0, 0.0, 0.0, 0.0), lambda: (v_mean_phi, sigma_R, sigma_z, sigma_phi))

    return output


get_jeans_moments_vmap = jax.vmap(get_jeans_moments, in_axes=(0,0,0,None,None,None,None))
# jeans_moments = get_jeans_moments(x_p, y_p, z_p, dict_phi, params_disk_rho,params_halo_pot, anisotropy_b=1.0)
def get_w0_new(w0, key1, key2, key3, n_particles):
    jeans_moments = get_jeans_moments_vmap(w0[:,0], w0[:,1], w0[:,2], dict_phi, params_disk_rho, params_halo_pot, 1.)
    v_rot, sig_R, sig_z, sig_phi = jeans_moments
    g1, g2, g3 = jax.random.normal(key1, (n_particles,)), jax.random.normal(key2, (n_particles,)), jax.random.normal(key3, (n_particles,))
    vR = g1 * sig_R # 2 sigma dispersion
    vz = g2 * sig_z
    vphi = v_rot + g3 * sig_phi
    x, y, vx, vy = getCartesianFromCylindrical_clockwise(jnp.sqrt(w0[:,0]**2 + w0[:,1]**2), jnp.arctan2(w0[:,1], w0[:,0]), vR, vphi)
    return jnp.array([x, y, w0[:,2], vx, vy, vz]).T
key1, key2, key3 = jax.random.PRNGKey(42), jax.random.PRNGKey(109), jax.random.PRNGKey(2026)
w0_new = get_w0_new(w0, key1, key2, key3, n_particles)


def _split(w):
    return w[:3], w[3:]

def _merge(r, v):
    return jnp.concatenate([r, v], axis=0)

@partial(jax.jit, static_argnames=('acc_fn', 'n_steps', 'unroll',))
def integrate_leapfrog_barred_traj(w0, acc_fn, n_steps, dt = 0.010, t0 = 0.0, Omega = 0.0, unroll=True):
    """Leapfrog (KDK) — returns final time and final state only.

    num_segments_Rzphi: int
        Number of segments for Rzphi bin counting. MUST equal to nRzphi.prod()
    num_segments_XY: int
        Number of segments for XY bin counting. MUST equal to nXY.prod()

    v0 and s are arrays of reference velocity and dispersion for each XY cell for the GH coefficent calculation. Length should equal to nXY.prod()
    """

    def step(carry, _):
        t, y = carry
        r, v = _split(y)

        # Gravity half-kick
        a0 = acc_fn(*r)
        v_half = v + 0.5 * dt * a0

        # Exact Omega-subflow for:
        #   xdot = vx + Omega*y, ydot = vy - Omega*x
        #   vxdot = Omega*vy,     vydot = -Omega*vx
        theta = Omega * dt
        c, s_theta = jnp.cos(theta), jnp.sin(theta)

        x_bar = r[0] + dt * v_half[0]
        y_bar = r[1] + dt * v_half[1]
        x_new = c * x_bar + s_theta * y_bar
        y_new = -s_theta * x_bar + c * y_bar
        z_new = r[2] + dt * v_half[2]

        vx_rot = c * v_half[0] + s_theta * v_half[1]
        vy_rot = -s_theta * v_half[0] + c * v_half[1]
        vz_rot = v_half[2]

        r_new = jnp.array([x_new, y_new, z_new])
        v_rot = jnp.array([vx_rot, vy_rot, vz_rot])
        t_new = t + dt

        # Gravity half-kick at updated position
        a1 = acc_fn(*r_new)
        v_new = v_rot + 0.5 * dt * a1
        y_new = _merge(r_new, v_new)
        return (t_new, y_new), (t_new, y_new)

    (_, _), (tN, wN) = jax.lax.scan(step, (t0, w0), xs=None, length=n_steps, unroll=unroll)

    return tN, wN

_R = jnp.sqrt(w0_new[:,0]**2 + w0_new[:,1]**2)
_z = w0_new[:,2]

T_orb = jax.vmap(estimate_orbital_timescale, in_axes=(0, None, None, 0))(
    _R,
    potential_func,
    (dict_phi, params_halo_pot),
    _z
)

N_step_per_orb = 100
N_dynamical_time = 50
dt = T_orb / N_step_per_orb
time_integrate = T_orb * N_dynamical_time
N_steps = N_step_per_orb * N_dynamical_time
#=========================================== Integrate orbits =======================================================
@jax.jit
def acc_fn(x, y, z):
    a_halo = NFW_acceleration(x, y, z,  params_halo_pot)
    a_disk = get_acc(x, y, z, dict_phi)
    return a_halo + a_disk

time_start = time.time()
_integrate_vmap = jax.vmap(integrate_leapfrog_barred_traj,
                        in_axes=(0, None, None, 0, None, None, None))
tN, wN = _integrate_vmap(w0_new, acc_fn, N_steps, dt, 0.0, -Omega_bar, False)
tN.block_until_ready()
time_end = time.time()
print(f"Time taken to integrate orbits with reconstructed potential: {time_end - time_start:.2f} seconds")
x_lf, y_lf, z_lf = wN[:,:,0].flatten(), wN[:,:,1].flatten(), wN[:,:,2].flatten()
vx_lf, vy_lf, vz_lf = wN[:,:,3].flatten(), wN[:,:,4].flatten(), wN[:,:,5].flatten()
print("Leapfrog integration done.")

alpha, beta, gamma = params_dict['alpha'], params_dict['beta'], params_dict['gamma']
rotation_matrix = makeRotationMatrix(alpha, beta, gamma)
num_Vbin = dict_data['total_bins']
bin_mapping, num_per_bin = dict_data['bin_mapping'], dict_data['num_per_bin']
v0, s = dict_data['v0'], dict_data['s']

_integrate_vmap = jax.vmap(integrate_leapfrog_barred,
                    in_axes=(
                            0, None, None, 0, None, None, None,
                              None, None, None,
                              None, None,
                              None, None, None,
                              None, None, None))

Rzphi_lim_grid = jnp.array([[0,10.],[-3,3],[-jnp.pi, jnp.pi]])
xy_lim_grid = jnp.array([[-12.,12.],[-4.,4.]])
Rzphi_n_grid = jnp.array([10,6,6])
xy_n_grid = jnp.array([60,40])
Rzphi_n_tot = 360

time_start = time.time()
Omega_bar = params_dict['Omega_bar']
# time = time_integrate #Gyr
n_steps = N_steps
dt = dt
unroll = False
initial_time = 0.0
Rzphi_bin_counts, surface_density, h1, h2, h3, h4 = _integrate_vmap(
                    w0_new, acc_fn, n_steps, dt, initial_time, -Omega_bar, unroll,
                    num_Vbin, bin_mapping, num_per_bin,
                    Rzphi_lim_grid, xy_lim_grid,
                    Rzphi_n_grid, xy_n_grid, Rzphi_n_tot,
                    v0, s, rotation_matrix)
Rzphi_bin_counts.block_until_ready()
A_Rzphi = Rzphi_bin_counts.T / n_steps
A_xy = surface_density.T / n_steps
A_h1 = h1.T
A_h2 = h2.T
A_h3 = h3.T
A_h4 = h4.T
time_end = time.time()
print(f"Time taken to integrate orbits and compute observables: {time_end - time_start:.2f} seconds")

@jax.jit
def density_func_Rz(R, z, phi, params):
    x = R * jnp.cos(phi)
    y = R * jnp.sin(phi)
    return density_func(x, y, z, params)
@partial(jax.jit, static_argnames=['rho_fct'])
def get_mass(R_grid, z_grid, phi_grid, rho_fct, dict_params, dR, dz, dphi, sample):
    R_samples = R_grid + (sample[:,0] - 0.5) * dR
    z_samples = z_grid + (sample[:,1] - 0.5) * dz
    phi_samples = phi_grid + (sample[:,2] - 0.5) * dphi
    density_samples = rho_fct(R_samples, z_samples, phi_samples, dict_params)
    mass_tot = jnp.sum(density_samples * R_samples) / sample.shape[0]
    return mass_tot
R_grid, dR = dict_data['R_grid'], dict_data['dR']
z_grid, dz = dict_data['z_grid'], dict_data['dz']
phi_grid, dphi = dict_data['phi_grid'], dict_data['dphi']
y_Rzphi = jax.vmap(get_mass, in_axes=[0, 0, 0, None, None, None, None, None, None])(
            R_grid, z_grid, phi_grid, density_func_Rz, params_dict, dR, dz, dphi, dict_data['sample_for_integration']
)
# y_Rzphi = dict_data['Rzphi_density_data'].astype(jnp.float32)
y_xy = dict_data['XY_density_data'].astype(jnp.float32)
y_h1 = dict_data['h1_data'].astype(jnp.float32)
y_h2 = dict_data['h2_data'].astype(jnp.float32)
y_h3 = dict_data['h3_data'].astype(jnp.float32)
y_h4 = dict_data['h4_data'].astype(jnp.float32)
y_xy = y_xy / params_dict['light_to_mass_ratio'] # convert from light to mass
sig_Rzphi = 0.02 * y_Rzphi + 1e-10
sig_xy = 0.01 * y_xy + 1e-10
# frac_err_min = 0.1
h_err_min = 0.03
sig_A1 = jnp.where(h_err_min > dict_data['h1_data_err'], h_err_min, dict_data['h1_data_err']) + EPSILON
sig_A2 = jnp.where(h_err_min > dict_data['h2_data_err'], h_err_min, dict_data['h2_data_err']) + EPSILON
sig_A3 = jnp.where(h_err_min > dict_data['h3_data_err'], h_err_min, dict_data['h3_data_err']) + EPSILON
sig_A4 = jnp.where(h_err_min > dict_data['h4_data_err'], h_err_min, dict_data['h4_data_err']) + EPSILON

mean_mass_per_orb = jnp.sum(y_Rzphi) / A_Rzphi.shape[1]

y_xy = y_xy / mean_mass_per_orb
sig_xy = sig_xy / mean_mass_per_orb
y_Rzphi = y_Rzphi / mean_mass_per_orb
sig_Rzphi = sig_Rzphi / mean_mass_per_orb

# path_data = '/Users/hanyuan/Desktop/PhD_projects/SchwarMAX_data/'
# with open(path_data + 'orbital_library_bar_2.pkl', 'wb') as f:
#     orb_lib = (A_Rzphi, A_xy, A_h1, A_h2, A_h3, A_h4, \
#         y_Rzphi, y_xy, y_h1, y_h2, y_h3, y_h4, \
#         sig_Rzphi, sig_xy, sig_A1, sig_A2, sig_A3, sig_A4)
#     pickle.dump(orb_lib, f)

from model import get_weights

solver = 'lbfgs'
solver_maxiter = 1000
solver_power_iters = 12
solver_cg_maxiter = 8
print('Weight solver:', solver)

time_start = time.time()
density_set, V_model, sigma_model, h1_set, h2_set, h3_set, h4_set,\
    density_unity_set, V_model_unity, sigma_model_unity, h1_unity_set, h2_unity_set, h3_unity_set, h4_unity_set,\
          weights = get_weights(A_Rzphi, A_xy, A_h1, A_h2, A_h3, A_h4,
        y_Rzphi, y_xy, y_h1, y_h2, y_h3, y_h4,
        sig_Rzphi, sig_xy, sig_A1, sig_A2, sig_A3, sig_A4, dict_data,
        solver=solver,
        solver_maxiter=solver_maxiter,
        solver_power_iters=solver_power_iters,
        solver_cg_maxiter=solver_cg_maxiter)
V_model.block_until_ready()
time_end = time.time()
print('Time taken to get weights:', time_end - time_start, 'seconds')

density_2DXY, y_xy, sig_xy = density_set
h1_model, y_h1, sig_A1 = h1_set
h2_model, y_h2, sig_A2 = h2_set
h3_model, y_h3, sig_A3 = h3_set
h4_model, y_h4, sig_A4 = h4_set

# V_model = jnp.where(jnp.isnan(V_model), 0.0, V_model)
# sigma_model = jnp.where(jnp.isnan(sigma_model), 0.0, sigma_model)
h3_model = jnp.where(jnp.isnan(h3_model), 0.0, h3_model)
h4_model = jnp.where(jnp.isnan(h4_model), 0.0, h4_model)
h1_data, h1_data_err = y_h1, sig_A1
h2_data, h2_data_err = y_h2, sig_A2
h3_data, h3_data_err = y_h3, sig_A3
h4_data, h4_data_err = y_h4, sig_A4

res_density = ((density_2DXY - y_xy) / (sig_xy + EPSILON))**2
res_h1 = ((h1_model - h1_data) / (h1_data_err + 1e-3))**2
res_h2 = ((h2_model - h2_data) / (h2_data_err + 1e-3))**2
res_h3 = ((h3_model - h3_data) / (h3_data_err + 1e-3))**2
res_h4 = ((h4_model - h4_data) / (h4_data_err + 1e-3))**2

res_h1 = jnp.where((h1_model < 9.9), res_h1, 0)
res_h2 = jnp.where((h2_model < 9.9), res_h2, 0)
res_h3 = jnp.where((h3_model < 9.9), res_h3, 0)
res_h4 = jnp.where((h4_model < 9.9), res_h4, 0)

val1 = jnp.nansum( -0.5 * res_density ) / len(density_2DXY)
val4 = jnp.nansum( -0.5 * res_h1 ) / len(h1_model)
val5 = jnp.nansum( -0.5 * res_h2 ) / len(h2_model)
val6 = jnp.nansum( -0.5 * res_h3 ) / len(h3_model)
val7 = jnp.nansum( -0.5 * res_h4 ) / len(h4_model)

log_likelihood = 0
log_likelihood += val1 + val4 + val5 + val6 + val7
print('log_likelihood:', log_likelihood)

A_Rzphi_run1 = A_Rzphi.copy()
A_xy_run1 = A_xy.copy()
A_h1_run1 = A_h1.copy()
A_h2_run1 = A_h2.copy()
A_h3_run1 = A_h3.copy()
A_h4_run1 = A_h4.copy()

A_Rzphi_run2 = A_Rzphi.copy()
A_xy_run2 = A_xy.copy()
A_h1_run2 = A_h1.copy()
A_h2_run2 = A_h2.copy()
A_h3_run2 = A_h3.copy()
A_h4_run2 = A_h4.copy()

(A_Rzphi_run1 - A_Rzphi_run2)

params_halo_pot = {
    'logM': ground_truth[0],
    'Rs':10 ** ground_truth[3],
    'a':1.0,
    'b':1.0,
    'c':1.0,
    'x_origin':0.0,
    'y_origin':0.0,
    'z_origin':0.0,
    'dirx':0.0,
    'diry':0.0,
    'dirz':1.0
}

x_orb = wN[:,:,0]
y_orb = wN[:,:,1]
z_orb = wN[:,:,2]
vx_orb = wN[:,:,3]
vy_orb = wN[:,:,4]
vz_orb = wN[:,:,5]
R_orb = jnp.sqrt(x_orb**2 + y_orb**2)
Lz_orb = (vx_orb * y_orb - vy_orb * x_orb)

E_pot = jax.vmap(potential_func, in_axes=(0, 0, 0, None, None))(x_orb, y_orb, z_orb, dict_phi, params_halo_pot)
E_kin = 0.5 * (vx_orb**2 + vy_orb**2 + vz_orb**2)
E_J = E_pot + E_kin - Omega_bar * Lz_orb

E_J.block_until_ready()
print('nothing', Omega_bar)

E_J_argsort = np.argsort(E_J[:,0])
E_J = E_J[E_J_argsort]

n_plot = 100
indices = np.random.choice(E_J.shape[0], n_plot, replace=False)
indices = np.sort(indices)

fig, axes = plt.subplots(10, 10, figsize=(20, 20))
axes = axes.flatten()

for i, ax in tqdm(enumerate(axes)):
    idx = indices[i]
    # Calculate fractional energy error
    y_vals = (E_J[idx, :] / E_J[idx, 0]) - 1
    ax.plot(y_vals)
    ax.grid(True)

    # Optional: reduce clutter
    ax.tick_params(axis='both', which='both', labelsize=6)
    # put E_J[idx, 0]/1e5 on title with 2 decimal
    ax.set_title(f'E_J x 1e5 = {E_J[idx, 0]/1e5:.2f}', fontsize=8)

fig.suptitle('50 timesteps per crossing time', fontsize = 18)
plt.tight_layout()
plt.show()

E_J_argsort = np.argsort(E_J[:,0])
E_J = E_J[E_J_argsort]

n_plot = 100
indices = np.random.choice(E_J.shape[0], n_plot, replace=False)
indices = np.sort(indices)

fig, axes = plt.subplots(10, 10, figsize=(20, 20))
axes = axes.flatten()

for i, ax in tqdm(enumerate(axes)):
    idx = indices[i]
    # Calculate fractional energy error
    y_vals = (E_J[idx, :] / E_J[idx, 0]) - 1
    ax.plot(y_vals)
    ax.grid(True)

    # Optional: reduce clutter
    ax.tick_params(axis='both', which='both', labelsize=6)
    # put E_J[idx, 0]/1e5 on title with 2 decimal
    ax.set_title(f'E_J x 1e5 = {E_J[idx, 0]/1e5:.2f}', fontsize=8)

fig.suptitle('100 timesteps per crossing time', fontsize = 18)
plt.tight_layout()
plt.show()

getCylindricalFromCartesian_clockwise

def getCylindricalFromCartesian_clockwise(x, y, vx, vy):
    R = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    vR = (x*vx + y*vy) / R
    vphi = -(x*vy - y*vx) / R
    return R, phi, vR, vphi

R_orb, phi_orb, vR_orb, vphi_orb = getCylindricalFromCartesian_clockwise(x_orb, y_orb, vx_orb, vy_orb)
mask_bad_orb = ((E_J[:,-1] - E_J[:,0]) / E_J[:,0]) < -0.99

print(mask_bad_orb.sum())

plt.figure(figsize=(16,4))
plt.subplot(1,3,1)
plt.scatter(x_orb[mask_bad_orb,0], y_orb[mask_bad_orb,0], s = 4, rasterized = True)
plt.xlim([-10,10])
plt.ylim([-10,10])

plt.subplot(1,3,2)
cb = plt.scatter(vR_orb[mask_bad_orb,0], vphi_orb[mask_bad_orb,0], c = R_orb[mask_bad_orb, 0], s = 4, rasterized = True)
plt.colorbar(cb)
plt.xlim([-200,200])
plt.ylim([-200,400])

plt.subplot(1,3,3)
cb = plt.scatter(vx_orb[mask_bad_orb,0], vz_orb[mask_bad_orb,0], c = np.fabs(z_orb)[mask_bad_orb, 0], s = 4, rasterized = True)
plt.colorbar(cb)
plt.xlim([-200,200])
plt.ylim([-200,200])

plt.figure(figsize=(16,4))
plt.subplot(1,3,1)
plt.hist(R_orb[mask_bad_orb, 0], bins = 30, density = True, histtype = 'step')
plt.hist(R_orb[:, 0], bins = 30, density = True, histtype = 'step')
plt.xlim([0,15])

plt.subplot(1,3,2)
plt.hist(z_orb[mask_bad_orb, 0], bins = 30, density = True, histtype = 'step')
plt.hist(z_orb[:, 0], bins = 30, density = True, histtype = 'step')
plt.xlim([0,5])

mask_bad_orb = ((E_J[:,-1] - E_J[:,0]) / E_J[:,0]) < -0.99
E_J_bad = E_J[mask_bad_orb]
x_bad_orb = x_orb[mask_bad_orb]
y_bad_orb = y_orb[mask_bad_orb]
z_bad_orb = z_orb[mask_bad_orb]
vx_bad_orb = vx_orb[mask_bad_orb]
vy_bad_orb = vy_orb[mask_bad_orb]
vz_bad_orb = vz_orb[mask_bad_orb]

n_plot = 25
indices = np.random.choice(E_J_bad.shape[0], n_plot, replace=False)
indices = np.sort(indices)

fig, axes = plt.subplots(5, 5, figsize=(20, 20))
axes = axes.flatten()

fig2, axes2 = plt.subplots(5, 5, figsize=(20, 20))
axes2 = axes2.flatten()

for i, ax in tqdm(enumerate(axes)):
    idx = indices[i]
    # Calculate fractional energy error
    y_vals = (E_J_bad[idx, :] / E_J_bad[idx, 0]) - 1
    ax.scatter(np.arange(0, len(y_vals), 1), y_vals, c = np.arange(0, len(y_vals), 1), s = 3)
    ax.grid(True)
    ax.tick_params(axis='both', which='both', labelsize=6)
    # put E_J[idx, 0]/1e5 on title with 2 decimal
    ax.set_title(f'E_J x 1e5 = {E_J[idx, 0]/1e5:.2f}', fontsize=8)

    axes2[i].scatter(x_bad_orb[idx, :], z_bad_orb[idx, :], c = np.arange(0, len(y_vals), 1), s = 3)
    axes2[i].grid(True)
    axes2[i].set_xlabel('x')
    axes2[i].set_ylabel('y')
    axes2[i].set(xlim = [-10,10], ylim=[-10,10])

fig.suptitle('100 timesteps per crossing time', fontsize = 18)
plt.tight_layout()
plt.show()

"""# Time for GPU saturation

"""

_integrate_vmap = jax.vmap(integrate_leapfrog_barred,
                    in_axes=(
                            0, None, None, 0, None, None, None,
                              None, None, None,
                              None, None,
                              None, None, None,
                              None, None, None))

path = '/content/drive/MyDrive/SchwarMAX-MCMC/'
dict_data = get_dict_data(path)

logMhalo_best_fit, logrho0_best_fit, logM_bar_best_fit, logRh_disk_best_fit, logRs_disk_best_fit, logHs_disk_best_fit, logRs_bar_best_fit,\
    alpha_best_fit, beta_best_fit, gamma_best_fit, logLM_best_fit, logOmega_bar = (11.8, 8.8, 10.4, 1.2, 0.45, -0.24, 0.3,
                                                                                    30*np.pi/180, 20*np.pi/180, 130*np.pi/180, 0, 1.6)

# logMhalo_best_fit, logrho0_best_fit, logM_bar_best_fit, logRh_disk_best_fit, logRs_disk_best_fit, logHs_disk_best_fit, logRs_bar_best_fit,\
#     alpha_best_fit, beta_best_fit, gamma_best_fit, logLM_best_fit, logOmega_bar = (10.07, 9.22, 9.2, 1.95, 0.54, -0.94, 0.35, 0.73, 0.71, 2.45, -0.25, 1.48)


alpha = alpha_best_fit * 180/np.pi
beta = beta_best_fit * 180/np.pi
gamma = gamma_best_fit * 180/np.pi
ground_truth = [logMhalo_best_fit,
                logrho0_best_fit,
                logM_bar_best_fit,
                logRh_disk_best_fit,
                logRs_disk_best_fit,
                logHs_disk_best_fit,
                logRs_bar_best_fit,
                alpha,
                beta,
                gamma,
                logLM_best_fit,
                logOmega_bar,
]


params_halo_pot = {
    'logM': ground_truth[0],
    'Rs':10 ** ground_truth[3],
    'a':1.0,
    'b':1.0,
    'c':1.0,
    'x_origin':0.0,
    'y_origin':0.0,
    'z_origin':0.0,
    'dirx':0.0,
    'diry':0.0,
    'dirz':1.0
}

params_dict = {
    'rho0_disc': 10 ** ground_truth[1],
    'Rd_disc': 10 ** ground_truth[4],
    'hz_disc': 10 ** ground_truth[5],
    'light_to_mass_ratio': 10 ** ground_truth[10],
    'x_origin': 0.0,
    'y_origin': 0.0,
    'z_origin': 0.0,
    'dirx': 0.0,
    'diry': 0.0,
    'dirz': 1.0,
    'alpha': ground_truth[7],
    'beta': ground_truth[8],
    'gamma': ground_truth[9],
    'logM_bar': ground_truth[2],
    'Rs_bar': 10 ** ground_truth[6],
    'Omega_bar': 10 ** ground_truth[11],
    'p_bar': 0.3,
    'q_bar': 0.3,
}

samples = np.array([
    np.random.normal(0, 5, 50_000),
    np.random.normal(0, 5, 50_000),
    np.random.normal(0, 2, 50_000)
]).T


w0 = jnp.array(samples)
n_particles = w0.shape[0]
params_disk_rho = params_dict
NR, NZ, Rmin, Rmax, Zmin, Zmax, Mmax = 50, 30, 1e-3, 30.0, 1e-3, 15.0, 8.
Nphi = 300
N_int = 10_000
dict_phi = get_phi_m(density_func, params_disk_rho, NR, NZ, Rmin, Rmax, Zmin, Zmax, Mmax, Nphi, N_int)

#=========================================== GET INITIAL VELOCITY ===================================================
@jax.jit
def dPhi_dz(x, y, z, dict_phi, params_halo):
    # Numerical derivative of Potential w.r.t z
    d = 5e-3
    return (potential_func(x, y, z+d, dict_phi, params_halo) - potential_func(x, y, z-d, dict_phi, params_halo)) / (2*d)

@jax.jit
def dPhi_dR(x, y, z, dict_phi, params_halo):
    # Numerical derivative of Potential w.r.t R
    d = 5e-3
    R = jnp.sqrt(x**2 + y**2)
    return (potential_func(R+d, 0, z, dict_phi, params_halo) - potential_func(R-d, 0, z, dict_phi, params_halo)) / (2*d)

@jax.jit
def get_jeans_moments(x_star, y_star, z_star, dict_phi, params_disc, params_halo, anisotropy_b=1.0):
    """
    Computes (v_mean, sigma_R, sigma_z, sigma_phi) for a star at (R, z).

    Parameters:
    -----------
    x_star, y_star, z_star : float
        Coordinates of the particle.
    density_fn : function
        Function returning stellar density nu(R, z).
    anisotropy_b : float
        sigma_R^2 / sigma_z^2. Default 1.0 (isotropic).
    """
    R_star = jnp.sqrt(x_star**2 + y_star**2)

    # --- Step 1: Compute Sigma_z (Vertical Integration) ---

    # Integrand: nu(R, z) * dPhi/dz
    def integrand(z_prime):
        return density_func(x_star, y_star, z_prime, params_disc) * dPhi_dz(x_star, y_star, z_prime, dict_phi, params_halo)

    # Integrate from z_star to infinity (e.g., 20 kpc)
    # Note: We assume symmetry, so we integrate |z| to infinity
    pts = jnp.linspace(jnp.abs(z_star), 10.0, 1000)
    dx = pts[1] - pts[0]
    # integrand_val = integrand(pts)
    integrand_val = jax.vmap(integrand, in_axes = (0))(pts)
    integral_val = jsp.integrate.trapezoid(integrand_val, pts, dx)

    nu_val = density_func(x_star, y_star, z_star, params_disc)
    # if nu_val <= 0: return 0, 0, 0, 0

    sigma_z2 = (1.0 / nu_val) * integral_val

    sigma_z2 = jnp.maximum(sigma_z2, 0.0)

    sigma_z = jnp.sqrt(sigma_z2)

    # --- Step 2: Compute Sigma_R (Anisotropy assumption) ---
    sigma_R2 = anisotropy_b * sigma_z2
    sigma_R = jnp.sqrt(sigma_R2)

    # --- Step 3: Compute v_phi_total^2 (Radial Equation) ---
    # We need d(nu * sigma_R^2) / dR
    # Since sigma_R^2 = b * sigma_z^2, we need d(b * Integral) / dR

    # Define a helper to calculate the "Vertical Pressure" P_zz = nu * sigma_z^2 at any R
    def vertical_pressure(r_in):
        # We need to re-integrate at radius r_in to get the pressure there
        def integrand_r(z_prime):
            return density_func(r_in, 0, z_prime, params_disc) * dPhi_dz(r_in, 0, z_prime, dict_phi, params_halo)

        pts = jnp.linspace(jnp.abs(z_star), 10.0, 1000)
        dx = pts[1] - pts[0]
        # integrand_val = integrand(pts)
        integrand_val = jax.vmap(integrand_r, in_axes = (0))(pts)
        integral_val = jsp.integrate.trapezoid(integrand_val, pts, dx)
        return integral_val # This is (nu * sigma_z^2)

    # Calculate derivative w.r.t R using central difference
    dR = 5e-3
    Pzz_plus = vertical_pressure(R_star + dR)
    Pzz_minus = vertical_pressure(R_star - dR)
    d_nu_sigR2_dR = anisotropy_b * (Pzz_plus - Pzz_minus) / (2*dR)

    # Radial Jeans Equation:
    # v_phi_sq = sigma_R^2 + (R/nu) * d(nu*sigR^2)/dR + R * dPhi/dR
    term1 = sigma_R2
    term2 = (R_star / nu_val) * d_nu_sigR2_dR
    term3 = R_star * dPhi_dR(x_star, y_star, z_star, dict_phi, params_halo)

    v_phi_total_sq = term1 + term2 + term3

    # --- Step 4: Separate Rotation vs Dispersion ---
    # Assumption: sigma_phi approx sigma_R (Round velocity ellipsoid in plane)
    sigma_phi = sigma_R

    v_streaming_sq = v_phi_total_sq - sigma_phi**2

    v_streaming_sq = jnp.maximum(v_streaming_sq, 0.0)
    v_mean_phi = jnp.sqrt(v_streaming_sq)

    output = jax.lax.cond(nu_val<=0, lambda: (0.0, 0.0, 0.0, 0.0), lambda: (v_mean_phi, sigma_R, sigma_z, sigma_phi))

    return output


get_jeans_moments_vmap = jax.vmap(get_jeans_moments, in_axes=(0,0,0,None,None,None,None))
# jeans_moments = get_jeans_moments(x_p, y_p, z_p, dict_phi, params_disk_rho,params_halo_pot, anisotropy_b=1.0)
def get_w0_new(w0, key1, key2, key3, n_particles):
    jeans_moments = get_jeans_moments_vmap(w0[:,0], w0[:,1], w0[:,2], dict_phi, params_disk_rho, params_halo_pot, 1.)
    v_rot, sig_R, sig_z, sig_phi = jeans_moments
    g1, g2, g3 = jax.random.normal(key1, (n_particles,)), jax.random.normal(key2, (n_particles,)), jax.random.normal(key3, (n_particles,))
    vR = g1 * sig_R # 2 sigma dispersion
    vz = g2 * sig_z
    vphi = v_rot + g3 * sig_phi
    x, y, vx, vy = getCartesianFromCylindrical_clockwise(jnp.sqrt(w0[:,0]**2 + w0[:,1]**2), jnp.arctan2(w0[:,1], w0[:,0]), vR, vphi)
    return jnp.array([x, y, w0[:,2], vx, vy, vz]).T
key1, key2, key3 = jax.random.PRNGKey(42), jax.random.PRNGKey(109), jax.random.PRNGKey(2026)
w0_new = get_w0_new(w0, key1, key2, key3, n_particles)


def _split(w):
    return w[:3], w[3:]

def _merge(r, v):
    return jnp.concatenate([r, v], axis=0)

@partial(jax.jit, static_argnames=('acc_fn', 'n_steps', 'unroll',))
def integrate_leapfrog_barred_traj(w0, acc_fn, n_steps, dt = 0.010, t0 = 0.0, Omega = 0.0, unroll=True):
    """Leapfrog (KDK) — returns final time and final state only.

    num_segments_Rzphi: int
        Number of segments for Rzphi bin counting. MUST equal to nRzphi.prod()
    num_segments_XY: int
        Number of segments for XY bin counting. MUST equal to nXY.prod()

    v0 and s are arrays of reference velocity and dispersion for each XY cell for the GH coefficent calculation. Length should equal to nXY.prod()
    """

    def step(carry, _):
        t, y = carry
        r, v = _split(y)

        # Gravity half-kick
        a0 = acc_fn(*r)
        v_half = v + 0.5 * dt * a0

        # Exact Omega-subflow for:
        #   xdot = vx + Omega*y, ydot = vy - Omega*x
        #   vxdot = Omega*vy,     vydot = -Omega*vx
        theta = Omega * dt
        c, s_theta = jnp.cos(theta), jnp.sin(theta)

        x_bar = r[0] + dt * v_half[0]
        y_bar = r[1] + dt * v_half[1]
        x_new = c * x_bar + s_theta * y_bar
        y_new = -s_theta * x_bar + c * y_bar
        z_new = r[2] + dt * v_half[2]

        vx_rot = c * v_half[0] + s_theta * v_half[1]
        vy_rot = -s_theta * v_half[0] + c * v_half[1]
        vz_rot = v_half[2]

        r_new = jnp.array([x_new, y_new, z_new])
        v_rot = jnp.array([vx_rot, vy_rot, vz_rot])
        t_new = t + dt

        # Gravity half-kick at updated position
        a1 = acc_fn(*r_new)
        v_new = v_rot + 0.5 * dt * a1
        y_new = _merge(r_new, v_new)
        return (t_new, y_new), (t_new, y_new)

    (_, _), (tN, wN) = jax.lax.scan(step, (t0, w0), xs=None, length=n_steps, unroll=unroll)

    return tN, wN

_R = jnp.sqrt(w0_new[:,0]**2 + w0_new[:,1]**2)
_z = w0_new[:,2]

T_orb = jax.vmap(estimate_orbital_timescale, in_axes=(0, None, None, 0))(
    _R,
    potential_func,
    (dict_phi, params_halo_pot),
    _z
)

N_step_per_orb = 100
N_dynamical_time = 50
dt = T_orb / N_step_per_orb
time_integrate = T_orb * N_dynamical_time
N_steps = N_step_per_orb * N_dynamical_time
#=========================================== Integrate orbits =======================================================
@jax.jit
def acc_fn(x, y, z):
    a_halo = NFW_acceleration(x, y, z,  params_halo_pot)
    a_disk = get_acc(x, y, z, dict_phi)
    return a_halo + a_disk


alpha, beta, gamma = params_dict['alpha'], params_dict['beta'], params_dict['gamma']
rotation_matrix = makeRotationMatrix(alpha, beta, gamma)
num_Vbin = dict_data['total_bins']
bin_mapping, num_per_bin = dict_data['bin_mapping'], dict_data['num_per_bin']
v0, s = dict_data['v0'], dict_data['s']

Rzphi_lim_grid = jnp.array([[0,10.],[-3,3],[-jnp.pi, jnp.pi]])
xy_lim_grid = jnp.array([[-12.,12.],[-4.,4.]])
Rzphi_n_grid = jnp.array([10,6,6])
xy_n_grid = jnp.array([60,40])
Rzphi_n_tot = 360

time_start = time.time()
Omega_bar = params_dict['Omega_bar']
# time = time_integrate #Gyr
n_steps = N_steps
dt = dt
unroll = False
initial_time = 0.0
Rzphi_bin_counts, surface_density, h1, h2, h3, h4 = _integrate_vmap(
                    w0_new, acc_fn, n_steps, dt, initial_time, -Omega_bar, unroll,
                    num_Vbin, bin_mapping, num_per_bin,
                    Rzphi_lim_grid, xy_lim_grid,
                    Rzphi_n_grid, xy_n_grid, Rzphi_n_tot,
                    v0, s, rotation_matrix)
Rzphi_bin_counts.block_until_ready()
A_Rzphi = Rzphi_bin_counts.T / n_steps
A_xy = surface_density.T / n_steps
A_h1 = h1.T
A_h2 = h2.T
A_h3 = h3.T
A_h4 = h4.T
time_end = time.time()
print(f"Time taken to integrate orbits and compute observables: {time_end - time_start:.2f} seconds")

N_particle_ls = np.geomspace(11, 61000, 10).astype(int)
time_ls = []
for N_particle in N_particle_ls:
  print(f"N_particle: {N_particle}")
  random_index = np.random.choice(500_000, size = N_particle, replace=True)
  w0_choose = w0_new[random_index, :]

  _integrate_vmap = jax.vmap(integrate_leapfrog_barred,
                    in_axes=(
                            0, None, None, 0, None, None, None,
                              None, None, None,
                              None, None,
                              None, None, None,
                              None, None, None))

  time_start = time.time()
  Omega_bar = params_dict['Omega_bar']
  # time = time_integrate #Gyr
  n_steps_choose = N_steps
  dt_choose = dt[random_index]
  unroll = False
  initial_time = 0.0
  Rzphi_bin_counts, surface_density, h1, h2, h3, h4 = _integrate_vmap(
                      w0_choose, acc_fn, n_steps_choose, dt_choose, initial_time, -Omega_bar, unroll,
                      num_Vbin, bin_mapping, num_per_bin,
                      Rzphi_lim_grid, xy_lim_grid,
                      Rzphi_n_grid, xy_n_grid, Rzphi_n_tot,
                      v0, s, rotation_matrix)
  Rzphi_bin_counts.block_until_ready()
  A_Rzphi = Rzphi_bin_counts.T / n_steps
  A_xy = surface_density.T / n_steps
  A_h1 = h1.T
  A_h2 = h2.T
  A_h3 = h3.T
  A_h4 = h4.T
  time_end = time.time()
  print(f"Time taken to integrate orbits and compute observables: {time_end - time_start:.2f} seconds")
  print(A_xy.shape)
  time_ls.append(time_end - time_start)

plt.plot(N_particle_ls, time_ls, marker = 's')
plt.xscale('log')
plt.xlabel('N particles')
plt.ylabel('Time (s)')