# -*- coding: utf-8 -*-
"""SchwarMAX-blackjax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xg11VgB9_pJtZBq5RFa59-B7KjpSfmff
"""

from google.colab import drive
drive.mount('/content/drive')

! pip install jaxopt
! pip install corner
! pip install emcee
!pip install blackjax jax==0.7.2 jaxlib==0.7.2

import os
# os.environ["JAX_ENABLE_X64"] = "True"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "true"
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = "0.95"
print(os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"])

path = '/content/drive/MyDrive/SchwarMAX-analytic/'

import sys
sys.path.append(path)

from model_bar import *
from likelihoods_bar import *
from utils import *
from sample_from_density import sample_from_density_grid

import jax
import jax.numpy as jnp

import jax
# jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import jax.numpy.linalg as jnn
import pandas as pd
import numpy as np
import scipy as sp
import pickle

import emcee
import corner
import matplotlib.pyplot as plt

import blackjax
from blackjax.smc.resampling import systematic
import time

from constants import EPSILON

# Commented out IPython magic to ensure Python compatibility.
path = '/content/drive/MyDrive/SchwarMAX-analytic/'
filename = 'mock_Nbody_bar_XY_withRot_gal2_Nbins1000.pkl'
dict_data = get_dict_data_bootstrap(path, filename)

def log_prior(theta,):
    if (7 < theta[0] < 12) and (8 < theta[1] < 12) and (-1 < theta[2] < 2) and (-1 < theta[3] < 1) and (-1 < theta[4] < 1)\
    and (0 <= theta[5] < jnp.pi) and (0 <= theta[6] < jnp.pi/2) and (0 <= theta[7] < jnp.pi):
        return 0.0  # log(1) = 0 for uniform prior
    return -np.inf  # log(0) = -inf for out-of-bounds

def log_prob(theta,):
    # print(theta)
    lp = log_prior(theta)
    if not np.isfinite(lp):
        return -np.inf

    ll = logl_density(theta, dict_data, dict_data['total_bins'])

    return ll + lp

ndim = 8
nwalkers = 16  # must be >= 2 * ndim

# Initialize walkers around ground truth
# p0 = np.array([ground_truth[k] for k in param_names])
p0 = np.array([10.5, 10, 0.8, 0., 0.5, jnp.pi/4, jnp.pi/4, 3.5*jnp.pi/4])
# initial_pos = p0 + 1e-1 * np.random.randn(nwalkers, ndim)
np.random.seed(42)
initial_pos = p0 + np.random.uniform(-0.3, 0.3, (nwalkers, ndim))

sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob)
sampler.run_mcmc(initial_pos, 500, progress=True)

samples = sampler.get_chain(discard=200, flat=True)


params_bestfit = np.percentile(samples, axis=0, q=50)
logl_val = logl_density(params_bestfit, dict_data, dict_data['total_bins'])
print('Best-fit logL projection', logl_val)#

dict_data['logl_density_max'] = logl_val

logM_disc_best_fit, logM_bulge_best_fit, \
logRd_disc_best_fit, logHs_disc_best_fit, logRs_bulge_best_fit, \
alpha_best_fit, beta_best_fit, gamma_best_fit = params_bestfit
# logMhalo_best_fit, logrho0_best_fit, logM_bulge_best_fit, logRh_disk_best_fit, logRs_disk_best_fit, logHs_disk_best_fit, logRs_bulge_best_fit,\
#       alpha_best_fit, beta_best_fit, gamma_best_fit, logLM_best_fit = (11.8, 8.8, 10.4, 1.2, 0.45, -0.24, -0.1, 30*np.pi/180, 20*np.pi/180, 0*np.pi/180, 0)

print('logM_disc_best_fit',logM_disc_best_fit)
print('logM_bulge_best_fit',logM_bulge_best_fit)
print('logRd_disc_best_fit',logRd_disc_best_fit)
print('logHs_disc_best_fit',logHs_disc_best_fit)
print('logRs_bulge_best_fit',logRs_bulge_best_fit)
print('alpha_best_fit',alpha_best_fit * 180 / np.pi)
print('beta_best_fit',beta_best_fit * 180 / np.pi)
print('gamma_best_fit',gamma_best_fit * 180 / np.pi)

ground_truth = [
    10.779253,
    # 11.9,
    logM_disc_best_fit,
    logM_bulge_best_fit,
    0.8970275,
    # 1.276,
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit, #  10 * np.pi/180,
    beta_best_fit,
    gamma_best_fit,
    0.,
    1.5,

    0.6, # sigma_xy model term
]

# Test 1: your proven working vmap
vmap_direct = jax.vmap(logl_angular_input_bootstrap, in_axes=(0, None, None))
test_params = jnp.array([ground_truth]*20)
# %time vmap_direct(test_params, dict_data, dict_data['total_bins']).block_until_ready()
# %time vmap_direct(test_params, dict_data, dict_data['total_bins']).block_until_ready()

fig, ax = plt.subplots(1,3,figsize=(14,3))

# reader = emcee.backends.HDFBackend(path + '/backend_0328_Nbins1000_withDens.csv', read_only=True)
# wholechain = reader.get_chain(discard=0, flat=False)
# logprob = reader.get_log_prob(discard=0, flat=False)
# posterior = wholechain[100:, (np.isfinite(logprob[-1, :]) & np.isfinite(logprob[50, :])), :]
# posterior = posterior.reshape(-1, posterior.shape[-1])
# emcee_mean = np.median(posterior, axis=0)
# emcee_std = np.std(posterior, axis=0)
# prior_center = emcee_mean
# print(prior_center)

logL_ls = []
for i in tqdm(range (0, 9)):
  params_i = [
    # 11.9,
    10.78,
    logM_disc_best_fit,
    logM_bulge_best_fit,
    # jnp.log10(19).item(),
    0.8970275,
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit,
    beta_best_fit,
    # gamma_best_fit,
    140*jnp.pi/180,
    0.,
    1.5,

    0.5,
  ]
  # params_i = prior_center.copy()
  params_i[-3] = params_i[-3] + (i-4)/10
  logL = logl_angular_input_bootstrap(params_i, dict_data, dict_data['total_bins'])
  logL.block_until_ready()  # Ensure computation finishes before timing
  print('L/M=', 10**params_i[-3], logL)
  logL_ls.append(logL)

ax[0].plot(np.arange(-4,5)/10 + ground_truth[-3], logL_ls - np.amin(np.isfinite(logL_ls)))
ax[0].set(xlabel = 'log10 (L/M)')

logL_ls = []
for i in tqdm(range (0, 9)):
  params_i = [
    # 11.9,
    10.78,
    logM_disc_best_fit,
    logM_bulge_best_fit,
    # jnp.log10(19).item(),
    0.9,
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit,
    beta_best_fit,
    gamma_best_fit,
    0.,
    1.5,

    0.5,
  ]
  # params_i = prior_center.copy()
  params_i[-2] = params_i[-2] + (i-4)/10
  logL = logl_angular_input_bootstrap(params_i, dict_data, dict_data['total_bins'])
  logL.block_until_ready()  # Ensure computation finishes before timing
  logL_ls.append(logL)
  print('Omega=', 10**params_i[-2], logL)

ax[1].plot(np.arange(-4,5)/10 + ground_truth[-2], logL_ls - np.amin(np.isfinite(logL_ls)))
ax[1].set(xlabel = 'log10 (Omega)')

logL_ls = []
for i in tqdm(range (0, 9)):
  params_i = [
    # 11.9,
    10.78,
    logM_disc_best_fit,
    logM_bulge_best_fit,
    # jnp.log10(19).item(),
    0.9,
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit,
    beta_best_fit,
    gamma_best_fit,
    0.,
    1.5,

    0.5,
  ]
  # params_i = prior_center.copy()
  params_i[-1] = params_i[-1] + (i-4)/10
  logL = logl_angular_input_bootstrap(params_i, dict_data, dict_data['total_bins'])
  logL.block_until_ready()  # Ensure computation finishes before timing
  logL_ls.append(logL)
  print('amplifier=', 10**params_i[-1], logL)

ax[2].plot(np.arange(-4,5)/10 + ground_truth[-1], logL_ls - np.amin(np.isfinite(logL_ls)))
ax[2].set(xlabel = ' log10(amplifier)')

ground_truth = [
    10.779253,
    # 11.9,
    logM_disc_best_fit,
    logM_bulge_best_fit,
    0.8970275,
    # 1.276,
    logRd_disc_best_fit,
    logHs_disc_best_fit,
    logRs_bulge_best_fit,
    alpha_best_fit, #  10 * np.pi/180,
    beta_best_fit,
    gamma_best_fit,
    0.,
    1.5,

    0.6, # sigma_xy model term
]
logL = logl_angular_input_bootstrap(ground_truth, dict_data, dict_data['total_bins'])
print(logL)

import time
start = time.time()
logL = logl_angular_input_bootstrap(ground_truth, dict_data, dict_data['total_bins'])
logL.block_until_ready()  # Ensure computation finishes before timing
end = time.time()
print('time per logl evaluation', end - start, 's')
print(logL)

path = '/content/drive/MyDrive/SchwarMAX-analytic/'

N_CHAINS = 16              # number of parallel chains (must fit in GPU vmap)
N_STEPS = 3000             # total MCMC steps per chain
CHECKPOINT_EVERY = 10
BURNIN = 600
ADAPT_EVERY = 100          # re-estimate covariance every N steps
ADAPT_AFTER = 300          # delay adaptation until chains have explored



CHECKPOINT_FILE = os.path.join(path, 'mcmc_checkpoint_gal2_0406.pkl')
OUTPUT_FILE = os.path.join(path, 'mcmc_results_gal2_0406.pkl')
OUTPUT_CSV = os.path.join(path, 'mcmc_posterior_gal2_0406.csv')


# ── Load data ────────────────────────────────────────────────────────
num_Vbin = int(dict_data['total_bins'])

# ── Best-fit point (for RMH proposal scaling) ────────────────────────
res = np.load(os.path.join(path, 'minimise_0329_gal2_Nbins1000.npy'))
res[-1] = 0.5

logM_10kpc, logC_halo = logM_logRs_to_logMenc_logc(res[0], res[3])
print('logM_10kpc', 'logC_halo', logM_10kpc, logC_halo)

res[0] = logM_10kpc
res[3] = logC_halo
# ── Prior bounds (13D) ───────────────────────────────────────────────
NDIM = 13
param_names = [
    'logM_10kpc', 'logM_disk', 'logM_bar', 'logC_halo', 'logRs_disk',
    'logHs_disk', 'logL_bar', 'alpha', 'beta', 'gamma',
    'log_light_to_mass_ratio', 'log_Omega', 'log_sigma',
]

BOUNDS_LO = jnp.array([
    res[0] - 3, res[1] - 3, res[2] - 3, res[3] - 1,
    res[4] - 1, res[5] - 1, res[6] - 1,
    0., 0., 0., -2., 0., -1.,
])
BOUNDS_HI = jnp.array([
    res[0] + 3, res[1] + 3, res[2] + 3, res[3] + 1,
    res[4] + 1, res[5] + 1, res[6] + 1,
    float(jnp.pi), float(jnp.pi / 2), float(jnp.pi), 2., 2., 2.,
])

# ── Log-posterior ────────────────────────────────────────────────────
def logdensity_fn(theta):
    in_bounds = jnp.all((theta >= BOUNDS_LO) & (theta <= BOUNDS_HI))
    log_vol = jnp.sum(jnp.log(BOUNDS_HI - BOUNDS_LO))
    logprior = jnp.where(in_bounds, -log_vol, -jnp.inf)

    ll = logl_angular_input_bootstrap(theta, dict_data, num_Vbin)
    ll = jnp.where(jnp.isfinite(ll), ll, -1e30)

    return logprior + ll

# ── Initial proposal (small for ~30-40% acceptance) ──────────────────
OPTIMAL_SCALE = 2.38 / np.sqrt(NDIM)  # Roberts & Rosenthal 2001

rmh_sigma_init = jnp.array([
    0.02, 0.02, 0.02, 0.01,
    0.01, 0.01, 0.01,
    0.01, 0.01, 0.02,
    0.02, 0.01,
    0.02,
])

# ── Helper: build sampler from proposal ──────────────────────────────
def build_sampler(proposal):
    rw = blackjax.additive_step_random_walk(logdensity_fn, proposal)
    return jax.vmap(rw.step)

# ── Initial positions ────────────────────────────────────────────────
def make_init_positions(rng_key):
    """Start chains near best-fit with small perturbation."""
    p0 = jnp.array(res)
    noise = jax.random.normal(rng_key, shape=(N_CHAINS, NDIM)) * rmh_sigma_init[None, :]
    positions = p0[None, :] + noise
    positions = jnp.clip(positions, BOUNDS_LO[None, :], BOUNDS_HI[None, :])
    return positions


# ── Checkpointing ───────────────────────────────────────────────────
def save_checkpoint(all_samples, all_logprob, step, rng_key, adapt_count=0,
                    proposal_L=None, scale_factor=1.0):
    ckpt = {
        'all_samples': [np.array(s) for s in all_samples],
        'all_logprob': [np.array(lp) for lp in all_logprob],
        'step': step,
        'rng_key': np.array(rng_key),
        'adapt_count': adapt_count,
        'proposal_L': np.array(proposal_L) if proposal_L is not None else None,
        'scale_factor': scale_factor,
    }
    with open(CHECKPOINT_FILE, 'wb') as f:
        pickle.dump(ckpt, f)


def load_checkpoint():
    if not os.path.exists(CHECKPOINT_FILE):
        return None
    with open(CHECKPOINT_FILE, 'rb') as f:
        ckpt = pickle.load(f)
    n_steps = len(ckpt['all_samples'])
    n_chains = ckpt['all_samples'][0].shape[0]
    print(f"Found checkpoint: {n_steps} steps, {n_chains} chains, "
          f"adapt_count={ckpt.get('adapt_count', 0)}")
    return ckpt


# ── Main loop ────────────────────────────────────────────────────────
def run_mcmc(resume=True):
    rng_key = jax.random.PRNGKey(42)

    ckpt = load_checkpoint() if resume else None

    if ckpt is not None:
        # ── Resume from checkpoint ────────────────────────────────
        all_positions = ckpt['all_samples']
        all_logprob = ckpt['all_logprob']
        start_step = ckpt['step']
        rng_key = jnp.array(ckpt['rng_key'])
        adapt_count = ckpt.get('adapt_count', 0)
        proposal_L = ckpt.get('proposal_L', None)
        scale_factor = ckpt.get('scale_factor', 1.0)

        # Reconstruct states from last saved positions/logprob
        last_positions = jnp.array(all_positions[-1])
        rw_init = blackjax.additive_step_random_walk(
            logdensity_fn, blackjax.mcmc.random_walk.normal(rmh_sigma_init))
        states = jax.vmap(rw_init.init)(last_positions)

        # Rebuild proposal from saved Cholesky factor
        if proposal_L is not None:
            proposal = blackjax.mcmc.random_walk.normal(
                jnp.array(proposal_L * scale_factor))
        else:
            proposal = blackjax.mcmc.random_walk.normal(rmh_sigma_init)
        vmap_step = build_sampler(proposal)

        print(f"Resumed from step {start_step}, {len(all_positions)} samples, "
              f"adapt_count={adapt_count}, scale_factor={scale_factor:.3f}")
    else:
        # ── Fresh start ───────────────────────────────────────────
        rng_key, init_key = jax.random.split(rng_key)
        positions = make_init_positions(init_key)

        print(f"Initialising {N_CHAINS} chains...")
        rw_init = blackjax.additive_step_random_walk(
            logdensity_fn, blackjax.mcmc.random_walk.normal(rmh_sigma_init))
        states = jax.vmap(rw_init.init)(positions)
        print(f"  Init done.")

        vmap_step = build_sampler(blackjax.mcmc.random_walk.normal(rmh_sigma_init))
        all_positions = []
        all_logprob = []
        start_step = 0
        adapt_count = 0
        proposal_L = None
        scale_factor = 1.0

    # Track recent acceptance (last ADAPT_EVERY steps)
    recent_accepts = []

    print(f"\nAdaptive RMH: {N_CHAINS} chains, {N_STEPS} steps, {NDIM}D")
    print(f"  Adapt covariance every {ADAPT_EVERY} steps after step {ADAPT_AFTER}")
    print(f"  Using all samples from step {ADAPT_AFTER} onward for covariance")
    print(f"  Optimal scale: {OPTIMAL_SCALE:.3f}")
    print(f"  Starting from step {start_step + 1}")

    pbar = tqdm(range(start_step + 1, N_STEPS + 1), desc="RMH", unit="step")
    for step in pbar:
        rng_key, step_key = jax.random.split(rng_key)
        keys = jax.random.split(step_key, N_CHAINS)

        states, infos = vmap_step(keys, states)

        all_positions.append(np.array(states.position))
        all_logprob.append(np.array(states.logdensity))

        step_accept = float(jnp.mean(infos.acceptance_rate))
        recent_accepts.append(step_accept)
        if len(recent_accepts) > ADAPT_EVERY:
            recent_accepts.pop(0)

        # ── Adapt proposal covariance ────────────────────────────
        if step >= ADAPT_AFTER and step % ADAPT_EVERY == 0:
            # Use samples from ADAPT_AFTER onward (skip burn-in)
            samples_post_burnin = np.stack(all_positions[int(ADAPT_AFTER-50):], axis=0)
            flat = samples_post_burnin.reshape(-1, NDIM)
            n_used = flat.shape[0]

            if n_used > 2 * NDIM:
                cov = np.cov(flat.T)
                diag = np.diag(np.diag(cov))
                cov_reg = 0.8 * cov + 0.2 * diag
                proposal_cov = OPTIMAL_SCALE**2 * cov_reg
                try:
                    L = np.linalg.cholesky(proposal_cov)
                    proposal_L = L

                    # Adjust scale based on recent acceptance
                    recent_acc = np.mean(recent_accepts)
                    # if recent_acc < 0.10:
                    #     scale_factor *= 0.8
                    # elif recent_acc > 0.35:
                    #     scale_factor *= 1.2
                    # scale_factor = np.clip(scale_factor, 0.1, 5.0)

                    proposal = blackjax.mcmc.random_walk.normal(
                        jnp.array(L * scale_factor))
                    vmap_step = build_sampler(proposal)
                    adapt_count += 1

                    tqdm.write(
                        f"  [Adapt #{adapt_count} at step {step}] "
                        f"recent_acc={recent_acc:.3f}, scale={scale_factor:.3f}, "
                        f"n={n_used}, "
                        f"cov diag={np.sqrt(np.diag(proposal_cov))[:3].round(4)}")
                except np.linalg.LinAlgError:
                    tqdm.write(f"  [Adapt #{adapt_count+1} at step {step}] "
                               f"Cholesky failed, keeping current proposal")
            else:
                tqdm.write(f"  [Adapt at step {step}] "
                           f"Too few samples ({n_used}), skipping")

        if step % 5 == 0:
            recent_acc = np.mean(recent_accepts) if recent_accepts else 0.0
            pbar.set_postfix(
                logP=f"{float(jnp.mean(states.logdensity)):.1f}",
                acc=f"{recent_acc:.3f}",
                adapt=adapt_count,
            )

        if step % CHECKPOINT_EVERY == 0:
            save_checkpoint(all_positions, all_logprob, step, rng_key,
                            adapt_count, proposal_L, scale_factor)

    # ── Results ──────────────────────────────────────────────────────
    chain = np.stack(all_positions, axis=0)  # (N_STEPS, N_CHAINS, NDIM)
    logprob = np.stack(all_logprob, axis=0)
    print(f"\nChain shape: {chain.shape}")

    # Flat samples after burn-in
    if chain.shape[0] > BURNIN:
        flat_samples = chain[BURNIN:].reshape(-1, NDIM)
    else:
        flat_samples = chain.reshape(-1, NDIM)

    print(f"\n── Posterior summary ({flat_samples.shape[0]} samples) ──")
    print(f"{'Parameter':>30s} {'mean':>10s} {'std':>10s} "
          f"{'2.5%':>10s} {'97.5%':>10s} {'truth':>10s}")
    print("-" * 82)
    for i, name in enumerate(param_names):
        s = flat_samples[:, i]
        truth = res[i]
        print(f"{name:>30s} {s.mean():10.4f} {s.std():10.4f} "
              f"{np.percentile(s, 2.5):10.4f} {np.percentile(s, 97.5):10.4f} "
              f"{truth:10.4f}")

    # Save
    results = {
        'chain': chain,
        'logprob': logprob,
        'flat_samples': flat_samples,
        'param_names': param_names,
    }
    with open(OUTPUT_FILE, 'wb') as f:
        pickle.dump(results, f)
    print(f"\nResults saved to {OUTPUT_FILE}")

    pd.DataFrame(flat_samples, columns=param_names).to_csv(OUTPUT_CSV, index=False)
    print(f"CSV saved to {OUTPUT_CSV}")

    return chain, logprob

if __name__ == '__main__':
    run_mcmc(resume = False)

path = '/content/drive/MyDrive/SchwarMAX-analytic/'

N_CHAINS = 40              # number of parallel chains (must fit in GPU vmap)
N_STEPS = 1500             # total MCMC steps per chain
CHECKPOINT_EVERY = 10
BURNIN = 300
ADAPT_EVERY = 100          # re-estimate covariance every N steps
ADAPT_AFTER = 300          # delay adaptation until chains have explored



CHECKPOINT_FILE = os.path.join(path, 'mcmc_checkpoint_gal2_0407.pkl')
OUTPUT_FILE = os.path.join(path, 'mcmc_results_gal2_0407.pkl')
OUTPUT_CSV = os.path.join(path, 'mcmc_posterior_gal2_0407.csv')


# ── Load data ────────────────────────────────────────────────────────
num_Vbin = int(dict_data['total_bins'])

# ── Best-fit point (for RMH proposal scaling) ────────────────────────
res = np.load(os.path.join(path, 'minimise_0329_gal2_Nbins1000.npy'))
res[-1] = 0.5

logM_10kpc, logC_halo = logM_logRs_to_logMenc_logc(res[0], res[3])
print('logM_10kpc', 'logC_halo', logM_10kpc, logC_halo)

res[0] = logM_10kpc
res[3] = logC_halo
# ── Prior bounds (13D) ───────────────────────────────────────────────
NDIM = 13
param_names = [
    'logM_10kpc', 'logM_disk', 'logM_bar', 'logC_halo', 'logRs_disk',
    'logHs_disk', 'logL_bar', 'alpha', 'beta', 'gamma',
    'log_light_to_mass_ratio', 'log_Omega', 'log_sigma',
]

BOUNDS_LO = jnp.array([
    res[0] - 3, res[1] - 3, res[2] - 3, res[3] - 1,
    res[4] - 1, res[5] - 1, res[6] - 1,
    0., 0., 0., -2., 0., -1.,
])
BOUNDS_HI = jnp.array([
    res[0] + 3, res[1] + 3, res[2] + 3, res[3] + 1,
    res[4] + 1, res[5] + 1, res[6] + 1,
    float(jnp.pi), float(jnp.pi / 2), float(jnp.pi), 2., 2., 2.,
])

# ── Log-posterior ────────────────────────────────────────────────────
def logdensity_fn(theta):
    in_bounds = jnp.all((theta >= BOUNDS_LO) & (theta <= BOUNDS_HI))
    log_vol = jnp.sum(jnp.log(BOUNDS_HI - BOUNDS_LO))
    logprior = jnp.where(in_bounds, -log_vol, -jnp.inf)

    ll = logl_angular_input_bootstrap(theta, dict_data, num_Vbin)
    ll = jnp.where(jnp.isfinite(ll), ll, -1e30)

    return logprior + ll

# ── Initial proposal (small for ~30-40% acceptance) ──────────────────
OPTIMAL_SCALE = 2.38 / np.sqrt(NDIM)  # Roberts & Rosenthal 2001

rmh_sigma_init = jnp.array([
    0.02, 0.02, 0.02, 0.01,
    0.01, 0.01, 0.01,
    0.01, 0.01, 0.02,
    0.02, 0.01,
    0.02,
])

# ── Helper: build sampler from proposal ──────────────────────────────
def build_sampler(proposal):
    rw = blackjax.additive_step_random_walk(logdensity_fn, proposal)
    return jax.vmap(rw.step), jax.vmap(rw.init)

N_HALF = N_CHAINS // 2  # each vmap batch size

def _split_pytree(tree):
    """Split a pytree of (N_CHAINS, ...) arrays into two halves."""
    return (jax.tree.map(lambda x: x[:N_HALF], tree),
            jax.tree.map(lambda x: x[N_HALF:], tree))

def _merge_pytree(tree0, tree1):
    """Merge two pytree halves back into (N_CHAINS, ...)."""
    return jax.tree.map(lambda a, b: jnp.concatenate([a, b], axis=0), tree0, tree1)

def batched_init(vmap_init, positions):
    """Initialise states in two batches to avoid OOM."""
    states_0 = vmap_init(positions[:N_HALF])
    states_1 = vmap_init(positions[N_HALF:])
    return _merge_pytree(states_0, states_1)

def batched_step(vmap_step, keys, states):
    """Run one MCMC step in two batches to avoid OOM."""
    states_0, states_1 = _split_pytree(states)
    keys_0, keys_1 = keys[:N_HALF], keys[N_HALF:]
    new_states_0, infos_0 = vmap_step(keys_0, states_0)
    new_states_1, infos_1 = vmap_step(keys_1, states_1)
    return _merge_pytree(new_states_0, new_states_1), _merge_pytree(infos_0, infos_1)

# ── Initial positions ────────────────────────────────────────────────
def make_init_positions(rng_key):
    """Start chains near best-fit with small perturbation."""
    p0 = jnp.array(res)
    noise = jax.random.normal(rng_key, shape=(N_CHAINS, NDIM)) * rmh_sigma_init[None, :]
    positions = p0[None, :] + noise
    positions = jnp.clip(positions, BOUNDS_LO[None, :], BOUNDS_HI[None, :])
    return positions


# ── Checkpointing ───────────────────────────────────────────────────
def save_checkpoint(all_samples, all_logprob, step, rng_key, adapt_count=0,
                    proposal_L=None, scale_factor=1.0):
    ckpt = {
        'all_samples': [np.array(s) for s in all_samples],
        'all_logprob': [np.array(lp) for lp in all_logprob],
        'step': step,
        'rng_key': np.array(rng_key),
        'adapt_count': adapt_count,
        'proposal_L': np.array(proposal_L) if proposal_L is not None else None,
        'scale_factor': scale_factor,
    }
    with open(CHECKPOINT_FILE, 'wb') as f:
        pickle.dump(ckpt, f)


def load_checkpoint():
    if not os.path.exists(CHECKPOINT_FILE):
        return None
    with open(CHECKPOINT_FILE, 'rb') as f:
        ckpt = pickle.load(f)
    n_steps = len(ckpt['all_samples'])
    n_chains = ckpt['all_samples'][0].shape[0]
    print(f"Found checkpoint: {n_steps} steps, {n_chains} chains, "
          f"adapt_count={ckpt.get('adapt_count', 0)}")
    return ckpt


# ── Main loop ────────────────────────────────────────────────────────
def run_mcmc(resume=True):
    rng_key = jax.random.PRNGKey(42)

    ckpt = load_checkpoint() if resume else None

    if ckpt is not None:
        # ── Resume from checkpoint ────────────────────────────────
        all_positions = ckpt['all_samples']
        all_logprob = ckpt['all_logprob']
        start_step = ckpt['step']
        rng_key = jnp.array(ckpt['rng_key'])
        adapt_count = ckpt.get('adapt_count', 0)
        proposal_L = ckpt.get('proposal_L', None)
        scale_factor = ckpt.get('scale_factor', 1.0)

        # Reconstruct states from last saved positions/logprob
        last_positions = jnp.array(all_positions[-1])
        if proposal_L is not None:
            proposal = blackjax.mcmc.random_walk.normal(
                jnp.array(proposal_L * scale_factor))
        else:
            proposal = blackjax.mcmc.random_walk.normal(rmh_sigma_init)
        vmap_step, vmap_init = build_sampler(proposal)
        states = batched_init(vmap_init, last_positions)

        print(f"Resumed from step {start_step}, {len(all_positions)} samples, "
              f"adapt_count={adapt_count}, scale_factor={scale_factor:.3f}")
    else:
        # ── Fresh start ───────────────────────────────────────────
        rng_key, init_key = jax.random.split(rng_key)
        positions = make_init_positions(init_key)

        print(f"Initialising {N_CHAINS} chains in 2 batches of {N_HALF}...")
        proposal_init = blackjax.mcmc.random_walk.normal(rmh_sigma_init)
        vmap_step, vmap_init = build_sampler(proposal_init)
        states = batched_init(vmap_init, positions)
        print(f"  Init done.")
        all_positions = []
        all_logprob = []
        start_step = 0
        adapt_count = 0
        proposal_L = None
        scale_factor = 1.0

    # Track recent acceptance (last ADAPT_EVERY steps)
    recent_accepts = []

    print(f"\nAdaptive RMH: {N_CHAINS} chains, {N_STEPS} steps, {NDIM}D")
    print(f"  Adapt covariance every {ADAPT_EVERY} steps after step {ADAPT_AFTER}")
    print(f"  Using all samples from step {ADAPT_AFTER} onward for covariance")
    print(f"  Optimal scale: {OPTIMAL_SCALE:.3f}")
    print(f"  Starting from step {start_step + 1}")

    pbar = tqdm(range(start_step + 1, N_STEPS + 1), desc="RMH", unit="step")
    for step in pbar:
        rng_key, step_key = jax.random.split(rng_key)
        keys = jax.random.split(step_key, N_CHAINS)

        states, infos = batched_step(vmap_step, keys, states)

        all_positions.append(np.array(states.position))
        all_logprob.append(np.array(states.logdensity))

        step_accept = float(jnp.mean(infos.acceptance_rate))
        recent_accepts.append(step_accept)
        if len(recent_accepts) > ADAPT_EVERY:
            recent_accepts.pop(0)

        # ── Adapt proposal covariance ────────────────────────────
        if step >= ADAPT_AFTER and step % ADAPT_EVERY == 0:
            # Use samples from ADAPT_AFTER onward (skip burn-in)
            samples_post_burnin = np.stack(all_positions[int(ADAPT_AFTER-50):], axis=0)
            flat = samples_post_burnin.reshape(-1, NDIM)
            n_used = flat.shape[0]

            if n_used > 2 * NDIM:
                cov = np.cov(flat.T)
                diag = np.diag(np.diag(cov))
                cov_reg = 0.8 * cov + 0.2 * diag
                proposal_cov = OPTIMAL_SCALE**2 * cov_reg
                try:
                    L = np.linalg.cholesky(proposal_cov)
                    proposal_L = L

                    recent_acc = np.mean(recent_accepts)
                    # # Adjust scale based on recent acceptance
                    #
                    # if recent_acc < 0.15:
                    #     scale_factor *= 0.8
                    # elif recent_acc > 0.35:
                    #     scale_factor *= 1.2
                    # scale_factor = np.clip(scale_factor, 0.1, 5.0)

                    proposal = blackjax.mcmc.random_walk.normal(
                        jnp.array(L * scale_factor))
                    vmap_step, _ = build_sampler(proposal)
                    adapt_count += 1

                    tqdm.write(
                        f"  [Adapt #{adapt_count} at step {step}] "
                        f"recent_acc={recent_acc:.3f}, scale={scale_factor:.3f}, "
                        f"n={n_used}, "
                        f"cov diag={np.sqrt(np.diag(proposal_cov))[:3].round(4)}")
                except np.linalg.LinAlgError:
                    tqdm.write(f"  [Adapt #{adapt_count+1} at step {step}] "
                               f"Cholesky failed, keeping current proposal")
            else:
                tqdm.write(f"  [Adapt at step {step}] "
                           f"Too few samples ({n_used}), skipping")

        if step % 10 == 0:
            recent_acc = np.mean(recent_accepts) if recent_accepts else 0.0
            pbar.set_postfix(
                logP=f"{float(jnp.mean(states.logdensity)):.1f}",
                acc=f"{recent_acc:.3f}",
                adapt=adapt_count,
            )

        if step % CHECKPOINT_EVERY == 0:
            save_checkpoint(all_positions, all_logprob, step, rng_key,
                            adapt_count, proposal_L, scale_factor)

    # ── Results ──────────────────────────────────────────────────────
    chain = np.stack(all_positions, axis=0)  # (N_STEPS, N_CHAINS, NDIM)
    logprob = np.stack(all_logprob, axis=0)
    print(f"\nChain shape: {chain.shape}")

    # Flat samples after burn-in
    if chain.shape[0] > BURNIN:
        flat_samples = chain[BURNIN:].reshape(-1, NDIM)
    else:
        flat_samples = chain.reshape(-1, NDIM)

    print(f"\n── Posterior summary ({flat_samples.shape[0]} samples) ──")
    print(f"{'Parameter':>30s} {'mean':>10s} {'std':>10s} "
          f"{'2.5%':>10s} {'97.5%':>10s} {'truth':>10s}")
    print("-" * 82)
    for i, name in enumerate(param_names):
        s = flat_samples[:, i]
        truth = res[i]
        print(f"{name:>30s} {s.mean():10.4f} {s.std():10.4f} "
              f"{np.percentile(s, 2.5):10.4f} {np.percentile(s, 97.5):10.4f} "
              f"{truth:10.4f}")

    # Save
    results = {
        'chain': chain,
        'logprob': logprob,
        'flat_samples': flat_samples,
        'param_names': param_names,
    }
    with open(OUTPUT_FILE, 'wb') as f:
        pickle.dump(results, f)
    print(f"\nResults saved to {OUTPUT_FILE}")

    pd.DataFrame(flat_samples, columns=param_names).to_csv(OUTPUT_CSV, index=False)
    print(f"CSV saved to {OUTPUT_CSV}")

    return chain, logprob


if __name__ == '__main__':
    run_mcmc(resume = True)